//! Typed events pushed from the Rust core to the UI.
//!
//! Rust owns sampling: the UI never polls. Every event type declared here is emitted at
//! a rate the core chooses (≤ 4 Hz for metric streams, per the resource budget) and its
//! TypeScript type is generated by `tauri-specta`.
//!
//! Payload fields stay within [`u32`]/[`f64`]: JavaScript numbers cannot represent the
//! full range of 64-bit integers, and `specta` rejects them rather than let a value
//! silently lose precision on the way to the UI.

use serde::{Deserialize, Serialize};
use specta::Type;

/// Liveness signal proving the Rust core is running and the event channel is wired.
///
/// Phase 0's demo event; the metric streams of later phases replace its role in the UI
/// but follow the same shape — Rust-driven, typed, batched.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Type, tauri_specta::Event)]
#[serde(rename_all = "camelCase")]
pub struct CoreHeartbeat {
    /// Monotonically increasing tick counter, wrapping at [`u32::MAX`].
    pub seq: u32,
    /// Whole seconds since the core started, measured on a monotonic clock.
    pub uptime_secs: u32,
}
