//! Typed events pushed from the Rust core to the UI.
//!
//! Rust owns sampling: the UI never polls. Every event type declared here is emitted at a
//! rate the core chooses (≤ 4 Hz for metric streams, per the resource budget) and its
//! TypeScript type is generated by `tauri-specta`.
//!
//! Payload fields stay within [`u32`]/[`f64`]: JavaScript numbers cannot represent the
//! full range of 64-bit integers, and `specta` rejects them rather than let a value
//! silently lose precision on the way to the UI.

use serde::{Deserialize, Serialize};
use specta::Type;

use crate::view::GroupView;

/// Liveness signal proving the Rust core is running and the event channel is wired.
///
/// Phase 0's demo event, kept because it is the one thing that distinguishes "nothing has
/// happened yet" from "the core is gone" before the first measurement lands.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Type, tauri_specta::Event)]
#[serde(rename_all = "camelCase")]
pub struct CoreHeartbeat {
    /// Monotonically increasing tick counter, wrapping at [`u32::MAX`].
    pub seq: u32,
    /// Whole seconds since the core started, measured on a monotonic clock.
    pub uptime_secs: u32,
}

/// The general-health picture: both baselines and every target in them.
///
/// Emitted once a second while the window is visible, and not at all while it is hidden —
/// see `crate::runtime`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Type, tauri_specta::Event)]
#[serde(rename_all = "camelCase")]
pub struct NetworkHealth {
    /// Whole seconds the core has been running, on a monotonic clock.
    pub uptime_secs: u32,
    /// Length of the window every figure is computed over, in seconds.
    pub window_secs: u32,
    /// The baselines, domestic first.
    pub groups: Vec<GroupView>,
}
