//! Typed events pushed from the Rust core to the UI.
//!
//! Rust owns sampling: the UI never polls. Every event type declared here is emitted at a
//! rate the core chooses (≤ 4 Hz for metric streams, per the resource budget) and its
//! TypeScript type is generated by `tauri-specta`.
//!
//! Payload fields stay within [`u32`]/[`f64`]: JavaScript numbers cannot represent the
//! full range of 64-bit integers, and `specta` rejects them rather than let a value
//! silently lose precision on the way to the UI.

use serde::{Deserialize, Serialize};
use specta::Type;

use crate::view::{AppView, DiagnosisView, FlowStatusView, NetworkSectionView};

/// Liveness signal proving the Rust core is running and the event channel is wired.
///
/// Phase 0's demo event, kept because it is the one thing that distinguishes "nothing has
/// happened yet" from "the core is gone" before the first measurement lands.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Type, tauri_specta::Event)]
#[serde(rename_all = "camelCase")]
pub struct CoreHeartbeat {
    /// Monotonically increasing tick counter, wrapping at [`u32::MAX`].
    pub seq: u32,
    /// Whole seconds since the core started, measured on a monotonic clock.
    pub uptime_secs: u32,
}

/// The Network page: every target, in four sections, and what they add up to.
///
/// Emitted once a second while the window is visible, and not at all while it is hidden —
/// see `crate::runtime`. Most emissions resend the same numbers, because the slowly checked
/// sections change on the scale of minutes; that is the right trade against a page that
/// would otherwise be blank for most of a minute after the user opened it.
///
/// One event, where there were two. The baselines and the service list were two payloads
/// carrying two shapes of the same object, and two of the foreign baseline's four entries
/// were the same addresses as two service endpoints — probed twice, drawn twice, in two
/// visual languages, under two names.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Type, tauri_specta::Event)]
#[serde(rename_all = "camelCase")]
pub struct NetworkSnapshot {
    /// Whole seconds the core has been running, on a monotonic clock.
    pub uptime_secs: u32,
    /// How many cells a full strip holds.
    ///
    /// Sent rather than counted from the cells, because a fresh endpoint has fewer of them
    /// and the page's legend states what a *full* strip covers. Without it the legend would
    /// either grow its own claim as the history filled or be arithmetic in the frontend.
    pub timeline_points: u32,
    /// What the two verdict-bearing sections say together.
    ///
    /// The comparison, not either one: domestic and foreign both failing points at the
    /// user's own line, domestic clean with foreign failing points at the path out of the
    /// country, and neither means much alone. It is the only claim on this page that is a
    /// conclusion rather than a measurement, and it stays a claim about a *network path* —
    /// never about a policy, a country or a company.
    pub diagnosis: DiagnosisView,
    /// The sections, in the order the page shows them.
    pub sections: Vec<NetworkSectionView>,
}

/// What every monitored application is talking to, and how each of those paths is doing.
///
/// Emitted on the same beat as [`NetworkHealth`], and like it, not at all while the window
/// is hidden. Sent even when nothing is monitored: the page still has to say whether flow
/// events are available, which decides whether an empty list means "this application has no
/// UDP endpoints" or "this machine cannot see UDP endpoints at all".
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Type, tauri_specta::Event)]
#[serde(rename_all = "camelCase")]
pub struct AppEndpoints {
    /// Length of the window every figure is computed over, in seconds.
    pub window_secs: u32,
    /// Span the byte counts accumulate over, in seconds.
    pub traffic_window_secs: u32,
    /// How much time one slot of the per-application chart covers, in seconds.
    ///
    /// Stated because it changes what a point *means*: each one is the slowest round trip
    /// inside its slot, and a break is a slot in which nothing answered. Both need the width
    /// of a slot to be readable.
    pub chart_step_secs: u32,
    /// Whether per-process flow events are available, and if not, why.
    pub flow_status: FlowStatusView,
    /// The monitored applications, in the order they were chosen.
    pub apps: Vec<AppView>,
}
