//! Tauri application layer for Network Monitor.
//!
//! Owns the process: the single tokio runtime, window/tray lifecycle, persistence and
//! the IPC surface. Business logic lives below in `nm-core`/`nm-probes`; this crate
//! wires it to the UI as typed commands (UI -> Rust) and typed events (Rust -> UI),
//! whose TypeScript definitions are generated by `tauri-specta` — never hand-written.
//!
//! Tests live in `tests/` rather than in `#[cfg(test)]` modules; see `tests.manifest`
//! for the Windows loader constraint that forces this.

#![warn(missing_docs)]

mod commands;
mod error;
mod events;
mod heartbeat;

pub use commands::{core_status, CoreReadiness, CoreStatus, PlatformKind};
pub use error::Error;
pub use events::CoreHeartbeat;

use tauri_specta::{collect_commands, collect_events};

/// Builds the typed IPC surface: every command the UI may call and every event the core
/// may push.
///
/// Public so the bindings exporter in `tests/` can generate `src/bindings.ts` from
/// exactly the surface the running app mounts — the two can never drift apart.
#[must_use]
pub fn ipc_builder() -> tauri_specta::Builder<tauri::Wry> {
    tauri_specta::Builder::<tauri::Wry>::new()
        .commands(collect_commands![commands::core_status])
        .events(collect_events![events::CoreHeartbeat])
}

/// Starts the desktop application and blocks until the user quits it.
///
/// # Errors
///
/// Returns [`Error::Runtime`] if the Tauri runtime cannot be built or fails while
/// running.
pub fn run() -> Result<(), Error> {
    let builder = ipc_builder();
    let invoke_handler = builder.invoke_handler();

    tauri::Builder::default()
        .invoke_handler(invoke_handler)
        .setup(move |app| {
            builder.mount_events(app);
            heartbeat::spawn(app.handle().clone());
            Ok(())
        })
        .run(tauri::generate_context!())?;

    Ok(())
}
