//! Tauri application layer for Network Monitor.
//!
//! Owns the process: the single tokio runtime, window/tray lifecycle, persistence and
//! the IPC surface. Business logic lives below in `nm-core`/`nm-probes`; this crate
//! wires it to the UI as typed commands (UI -> Rust) and typed events (Rust -> UI),
//! whose TypeScript definitions are generated by `tauri-specta` — never hand-written.
//!
//! # The shape of a running app
//!
//! [`run`] starts three long-lived tasks and then gets out of the way:
//!
//! * `runtime` probes the baselines and the monitored applications' discovered endpoints,
//!   and pushes a health snapshot once a second — but only while the window is visible.
//!   Hidden means "stop drawing", never "stop measuring".
//! * `settings` writes the configuration back to disk, debounced, so a dragged slider is
//!   one write rather than one per frame.
//! * `heartbeat` proves the event channel is alive before the first measurement lands.
//!
//! Tests live in `tests/` rather than in `#[cfg(test)]` modules; see `tests.manifest`
//! for the Windows loader constraint that forces this, and note that the library target
//! sets `test = false`, so an in-crate test module would never run at all.

#![warn(missing_docs)]
// The app layer wires crates together; it has no business dereferencing raw pointers.
#![forbid(unsafe_code)]

mod commands;
mod error;
mod events;
mod heartbeat;
mod runtime;
mod shell;
mod state;
mod view;

pub mod applications;
pub mod apps;
pub mod baselines;
pub mod discovery;
pub mod monitor;
pub mod presets;
pub mod settings;

pub use commands::{
    core_status, list_applications, CoreReadiness, CoreStatus, PlatformKind, SettingsView,
};
pub use error::Error;
pub use events::{AppEndpoints, CoreHeartbeat, NetworkHealth};
pub use shell::TrayLabels;
pub use view::{
    AppProcessView, AppView, ApplicationChoiceView, ApplicationListProblem, ApplicationListView,
    EndpointView, FlowStatusView, FlowView, GroupView, HealthCountsView, HealthView, LivenessView,
    PassiveRttView, ProbeKindView, ProbingView, TargetView, TransportView, SERIES_POINTS,
};

use std::path::PathBuf;
use std::sync::atomic::AtomicBool;
use std::sync::Arc;

use tauri::Manager as _;
use tauri_specta::{collect_commands, collect_events};

use crate::settings::SettingsProblem;
use crate::state::AppState;

/// Builds the typed IPC surface: every command the UI may call and every event the core
/// may push.
///
/// Public so the bindings exporter in `tests/` can generate `src/bindings.ts` from
/// exactly the surface the running app mounts — the two can never drift apart.
#[must_use]
pub fn ipc_builder() -> tauri_specta::Builder<tauri::Wry> {
    tauri_specta::Builder::<tauri::Wry>::new()
        .commands(collect_commands![
            commands::core_status,
            commands::get_settings,
            commands::set_settings,
            commands::list_applications,
            commands::monitor_app,
            commands::forget_app,
            commands::apply_tray_labels,
            commands::hide_to_tray,
            commands::quit_app,
        ])
        .events(collect_events![
            events::CoreHeartbeat,
            events::NetworkHealth,
            events::AppEndpoints
        ])
}

/// Starts the desktop application and blocks until the user quits it.
///
/// # Errors
///
/// Returns [`Error::Runtime`] if the Tauri runtime cannot be built or fails while
/// running.
pub fn run() -> Result<(), Error> {
    let builder = ipc_builder();
    let invoke_handler = builder.invoke_handler();

    tauri::Builder::default()
        // Registered first, as the plugin requires: a second launch hands its arguments to
        // the running instance instead of starting a second set of probes.
        .plugin(tauri_plugin_single_instance::init(|app, _argv, _cwd| {
            shell::show_window(app);
        }))
        .plugin(tauri_plugin_autostart::init(
            tauri_plugin_autostart::MacosLauncher::LaunchAgent,
            None,
        ))
        .invoke_handler(invoke_handler)
        .setup(move |app| {
            builder.mount_events(app);
            let handle = app.handle().clone();

            let path = settings_path(&handle);
            let loaded = path.as_deref().map_or_else(
                || crate::settings::Loaded {
                    settings: crate::settings::Settings::default(),
                    problem: Some(SettingsProblem::NotWritable),
                },
                crate::settings::load,
            );

            let (changes, receiver) = tokio::sync::watch::channel(loaded.settings.clone());
            if let Some(path) = path {
                crate::settings::spawn_writer(path, receiver);
            }

            // The window starts visible, per `tauri.conf.json`.
            let visible = Arc::new(AtomicBool::new(true));
            let monitor = runtime::spawn(
                handle.clone(),
                loaded.settings.clone(),
                Arc::clone(&visible),
            );

            app.manage(AppState::new(
                changes,
                loaded.problem,
                monitor,
                Arc::clone(&visible),
            ));

            shell::install_tray(&handle)?;
            heartbeat::spawn(handle, visible);
            Ok(())
        })
        .on_window_event(|window, event| {
            if let tauri::WindowEvent::CloseRequested { api, .. } = event {
                let app = window.app_handle();
                // Minimizing to the tray is only safe once there is a menu to come back
                // from; before that, the close means what it says.
                if app
                    .try_state::<AppState>()
                    .is_some_and(|state| state.can_minimize_to_tray())
                {
                    api.prevent_close();
                    shell::hide_window(app);
                }
            }
        })
        .run(tauri::generate_context!())?;

    Ok(())
}

/// Where the settings file lives, when the platform can tell us.
///
/// [`None`] means no per-user configuration directory could be resolved, in which case the
/// app runs on defaults and says so rather than writing somewhere arbitrary.
fn settings_path(app: &tauri::AppHandle<tauri::Wry>) -> Option<PathBuf> {
    app.path()
        .app_config_dir()
        .ok()
        .map(|directory| directory.join(settings::FILE_NAME))
}
