//! Known-application presets: which executables belong to one application, and what to
//! call them.
//!
//! **Two jobs, deliberately separated.** *Grouping* joins several executables into one
//! application; *labelling* gives one executable a name. A launcher and the title it starts
//! need the first; a single-process game needs only the second, and today it would appear in
//! the picker as `WorldOfTanks.exe` — which makes the page read like a task manager.
//!
//! The separation matters most for the one rule that protects the user. "Never list an
//! executable several applications share" is a rule about **grouping**: listing `steam.exe`
//! in a grouping entry would silently merge two games the user chose separately. Labelling
//! it "Steam" joins nothing to it and is safe, which is why the two live in different lists
//! with different validation.
//!
//! An application is not a process, and most of the grouping needs no data at all — the
//! executable name catches an Electron application's helpers, and the process tree catches
//! a launcher starting a title. The grouping list is for what those two rules cannot see: a
//! title whose companion executable is neither its parent nor its namesake.
//!
//! The list is `assets/apps/presets.json`, compiled in with [`include_str!`] exactly like
//! the baseline target lists, so the app never fetches it and cannot be made to.
//! `assets/apps/README.md` documents the schema and the rules for adding an entry —
//! including the one that matters most: never list an executable that several applications
//! share, or picking one game would silently drag another into it.
//!
//! # Why `deny_unknown_fields`
//!
//! The same reasoning as the target lists. A misspelled key here is an executable that will
//! never be grouped, and a grouping that silently fails to happen is invisible: the user
//! sees an application that is missing half its endpoints and no reason why. Loud is the
//! only safe failure.

use std::collections::HashMap;
use std::sync::OnceLock;

use serde::Deserialize;

use crate::Error;

/// The schema version this build understands.
const SUPPORTED_SCHEMA: u32 = 1;

/// The bundled presets.
const PRESETS_JSON: &str = include_str!("../../../../assets/apps/presets.json");

/// The bundled name catalogue, generated by `scripts/build-app-labels.mjs`.
const LABELS_JSON: &str = include_str!("../../../../assets/apps/labels.json");

/// The generated catalogue, parsed at most once in the life of the process.
///
/// Nine thousand names is half a megabyte of text, and [`PresetList::bundled`] is called
/// every time the picker is opened. Parsing it per call would put ten milliseconds of
/// string allocation behind a button press for a table that cannot change between builds.
static CATALOGUE: OnceLock<HashMap<String, String>> = OnceLock::new();

/// A catalogue with nothing in it, for lists that were not built from the bundled file.
static NO_CATALOGUE: OnceLock<HashMap<String, String>> = OnceLock::new();

fn no_catalogue() -> &'static HashMap<String, String> {
    NO_CATALOGUE.get_or_init(HashMap::new)
}

/// The generated executable-to-title catalogue.
///
/// A failure here costs names and nothing else, so it degrades to an empty catalogue rather
/// than to an error the caller would have to explain: every grouping, every measurement and
/// every verdict is unaffected by a file that only decides what things are called. A test
/// asserts the bundled file parses, so this is a build-time guarantee rather than a hope.
fn catalogue() -> &'static HashMap<String, String> {
    CATALOGUE.get_or_init(|| {
        serde_json::from_str::<Catalogue>(LABELS_JSON)
            .map(|parsed| parsed.labels)
            .unwrap_or_default()
    })
}

/// The generated catalogue's file format.
///
/// A map rather than a list of records: the keys are already the lowercased base names the
/// lookup compares against, which is both the smallest form and the one that cannot carry a
/// duplicate.
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct Catalogue {
    /// Schema version of the file. Read so a future format can be told apart from this one.
    #[allow(dead_code)]
    schema_version: u32,
    /// Where the names came from, for provenance. See `assets/apps/README.md`.
    #[allow(dead_code)]
    source: String,
    /// Lowercased executable file name to the title it belongs to.
    labels: HashMap<String, String>,
}

/// One application whose processes cannot be grouped from the operating system alone.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Preset {
    /// Stable identifier, unique in the file. Never shown to the user.
    pub id: String,
    /// The application's own name for itself. A proper noun: shown as written, never
    /// translated.
    pub label: String,
    /// Executable names that belong to this application, compared case-insensitively —
    /// which is how Windows compares them.
    ///
    /// The first is the one the application is named after when several are running.
    pub executables: Vec<String>,
}

impl Preset {
    /// Whether an executable name belongs to this application.
    #[must_use]
    pub fn covers(&self, executable: &str) -> bool {
        self.executables
            .iter()
            .any(|known| known.eq_ignore_ascii_case(executable))
    }
}

/// A name for one executable, joining nothing to it.
///
/// The other half of what this file does. A game that is a single process needs no grouping
/// and still deserves its own name rather than its file name, and a launcher several games
/// share — `steam.exe`, `EpicGamesLauncher.exe` — can be *named* safely precisely because
/// naming joins nothing: the user who picks it gets the launcher and whatever it starts,
/// which is what they asked for, and no other application is dragged in.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Label {
    /// Stable identifier, unique in the file. Never shown to the user.
    pub id: String,
    /// The application's own name for itself. A proper noun: shown as written, never
    /// translated.
    pub label: String,
    /// The executable it names, compared case-insensitively.
    pub executable: String,
}

/// The parsed preset file.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PresetList {
    /// Schema version of the file.
    pub schema_version: u32,
    /// The applications whose processes must be grouped, in file order.
    pub applications: Vec<Preset>,
    /// Executables that need only a name, in file order.
    ///
    /// Defaulted so a file written before this list existed still loads: an absent name is a
    /// missing label, which is a cosmetic loss, while refusing the file would cost every
    /// grouping in it.
    #[serde(default)]
    pub labels: Vec<Label>,
    /// The generated catalogue this list consults after its own two lists.
    ///
    /// Empty unless the list came from [`PresetList::bundled`], which is what keeps a
    /// hand-written list in a test to exactly the entries the test wrote. Borrowed rather
    /// than owned so that building a list stays the cost of parsing a page of JSON.
    #[serde(skip, default = "no_catalogue")]
    catalogue: &'static HashMap<String, String>,
}

impl PresetList {
    /// Parses and validates a preset file.
    ///
    /// # Errors
    ///
    /// Returns [`Error::AppPresets`] for malformed JSON, an unsupported schema version, an
    /// empty or duplicated identifier, a preset with no executables, or — the one that
    /// actually protects the user — an executable claimed by two presets. That last one
    /// would make grouping depend on file order, which is to say on nothing the user can
    /// see, so it is refused rather than resolved.
    pub fn parse(json: &str) -> Result<Self, Error> {
        let list: Self = serde_json::from_str(json).map_err(|source| Error::AppPresets {
            reason: source.to_string(),
        })?;

        let complain = |reason: String| Error::AppPresets { reason };

        if list.schema_version != SUPPORTED_SCHEMA {
            return Err(complain(format!(
                "schema version {} is not supported (this build understands {SUPPORTED_SCHEMA})",
                list.schema_version
            )));
        }

        for (index, preset) in list.applications.iter().enumerate() {
            if preset.id.is_empty() || preset.label.is_empty() {
                return Err(complain(format!("preset {index} has an empty id or label")));
            }
            if preset.executables.is_empty() {
                return Err(complain(format!(
                    "preset {:?} lists no executables",
                    preset.id
                )));
            }
            if preset.executables.iter().any(String::is_empty) {
                return Err(complain(format!(
                    "preset {:?} lists an empty executable name",
                    preset.id
                )));
            }
            for earlier in &list.applications[..index] {
                if earlier.id == preset.id {
                    return Err(complain(format!("duplicate preset id {:?}", preset.id)));
                }
                if let Some(shared) = preset
                    .executables
                    .iter()
                    .find(|executable| earlier.covers(executable))
                {
                    return Err(complain(format!(
                        "{shared:?} is claimed by both {:?} and {:?}",
                        earlier.id, preset.id
                    )));
                }
            }
        }

        for (index, entry) in list.labels.iter().enumerate() {
            if entry.id.is_empty() || entry.label.is_empty() || entry.executable.is_empty() {
                return Err(complain(format!(
                    "label {index} has an empty id, label or executable"
                )));
            }
            if list.applications.iter().any(|preset| preset.id == entry.id)
                || list.labels[..index]
                    .iter()
                    .any(|other| other.id == entry.id)
            {
                return Err(complain(format!("duplicate id {:?}", entry.id)));
            }
            // A grouping entry already names its executables. Two sources for one name would
            // make the label depend on which list was consulted first, which is to say on
            // nothing the reader of this file can see.
            if let Some(preset) = list.matching(&entry.executable) {
                return Err(complain(format!(
                    "{:?} is already named by the grouping entry {:?}",
                    entry.executable, preset.id
                )));
            }
            if list.labels[..index]
                .iter()
                .any(|other| other.executable.eq_ignore_ascii_case(&entry.executable))
            {
                return Err(complain(format!(
                    "{:?} is labelled twice",
                    entry.executable
                )));
            }
        }

        Ok(list)
    }

    /// Loads the bundled presets.
    ///
    /// # Errors
    ///
    /// Returns [`Error::AppPresets`] when the bundled file does not validate. A test
    /// asserts it does, so this is a build-time guarantee rather than a runtime hope.
    pub fn bundled() -> Result<Self, Error> {
        let mut list = Self::parse(PRESETS_JSON)?;
        // Consulted only after the curated lists, and the generator already removed anything
        // they speak for — so the curated file wins twice over, by construction and by order.
        list.catalogue = catalogue();
        Ok(list)
    }

    /// A list that groups nothing.
    ///
    /// What the app falls back to if the bundled file ever failed to load: the executable
    /// name and the process tree still group most applications correctly, so losing the
    /// presets costs the awkward titles and nothing else.
    #[must_use]
    pub fn empty() -> Self {
        Self {
            schema_version: SUPPORTED_SCHEMA,
            applications: Vec::new(),
            labels: Vec::new(),
            catalogue: no_catalogue(),
        }
    }

    /// The preset an executable belongs to, if any.
    ///
    /// **Grouping only.** A label is not a preset and can never join one process to another,
    /// which is why it is not reachable through here.
    #[must_use]
    pub fn matching(&self, executable: &str) -> Option<&Preset> {
        self.applications
            .iter()
            .find(|preset| preset.covers(executable))
    }

    /// What to call an executable, from the curated lists first and the catalogue after.
    ///
    /// [`None`] means nothing knows a name for it and the file name is the honest answer —
    /// never a name inferred from the file name, which would be a guess wearing a proper
    /// noun's clothes.
    ///
    /// The order is the guarantee: a curated entry always wins, so correcting a name the
    /// generated catalogue got wrong is one line in `presets.json` rather than an argument
    /// with a table of nine thousand entries.
    #[must_use]
    pub fn label_of(&self, executable: &str) -> Option<&str> {
        if let Some(preset) = self.matching(executable) {
            return Some(&preset.label);
        }
        if let Some(entry) = self
            .labels
            .iter()
            .find(|entry| entry.executable.eq_ignore_ascii_case(executable))
        {
            return Some(&entry.label);
        }
        self.catalogue
            .get(&executable.to_lowercase())
            .map(String::as_str)
    }
}
