//! What the UI is told, and nothing more.
//!
//! These are the serialisable shapes that cross the IPC boundary; their TypeScript
//! definitions are generated by `tauri-specta`. They mirror the core's own enums rather
//! than re-exporting them, which keeps `nm-core` free of serialisation concerns and keeps
//! the wire format from drifting whenever an internal type gains a field.
//!
//! Two rules run through everything here:
//!
//! * **Absent knowledge stays absent.** Every measured quantity is an [`Option`], so a
//!   target with nothing to report renders as "—" and never as `0`.
//! * **Enums, not prose.** The UI maps each variant to a translation key in an exhaustive
//!   `switch`, so a new variant is a TypeScript compile error rather than a missing string
//!   at runtime.

use std::time::Duration;

use nm_core::diagnosis::{AppEvidence, BaselineEvidence, Diagnosis, Evidence, Verdict};
use nm_core::edge::{EdgeReading, PathQuality};
use nm_core::endpoint::{Liveness, Probing, Transport};
use nm_core::health::{GroupHealth, Health, HealthCounts};
use nm_core::path::PathEnd;
use nm_core::pool::PoolReading;
use nm_core::status::CheckMark;
use nm_platform::interface::InterfaceNames;
use nm_probes::probe::ProbeKind;
use serde::{Deserialize, Serialize};
use specta::Type;

use crate::apps::{EndpointAge, EndpointReport, PassiveRttReading};
use crate::asn::{NetworkNames, NetworkView};
use crate::baselines::BaselineGroup;
use crate::discovery::FlowStatus;
use crate::services::ServiceGroup;

/// How many samples of a target's history the sparkline carries.
///
/// Sixty points is a legible sparkline and, at the default five-second baseline interval,
/// five minutes of history. Larger would cost IPC bandwidth every second for detail no
/// pixel could show.
pub const SERIES_POINTS: usize = 60;

/// How something is doing — one target or a whole group.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub enum HealthView {
    /// Answering, within every threshold.
    Ok,
    /// Answering, but losing packets, slow or unstable.
    Degraded,
    /// Nothing gets through, or the destination refuses.
    Unreachable,
    /// Every probe was filtered; nothing about the link was measured.
    Blocked,
    /// Data is crossing it, but no probe answers — the normal state of a game server.
    CarryingTraffic,
    /// Not measured enough yet to say anything.
    Unknown,
}

impl From<Health> for HealthView {
    fn from(health: Health) -> Self {
        match health {
            Health::Ok => Self::Ok,
            Health::Degraded => Self::Degraded,
            Health::Unreachable => Self::Unreachable,
            Health::Blocked => Self::Blocked,
            Health::CarryingTraffic => Self::CarryingTraffic,
            // A core that grows a state the UI has no word for must render as "unknown"
            // rather than as anything reassuring.
            _ => Self::Unknown,
        }
    }
}

/// Which probe kind produced a target's numbers.
///
/// Shown because it changes what the number means: a TLS figure through a tunnel is not
/// the same quantity as an ICMP round trip to a server.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub enum ProbeKindView {
    /// An ICMP echo.
    IcmpEcho,
    /// A bare TCP connection attempt.
    TcpConnect,
    /// A TLS `ClientHello`, timed to the first answering byte.
    TlsHello,
}

impl From<ProbeKind> for ProbeKindView {
    fn from(kind: ProbeKind) -> Self {
        match kind {
            ProbeKind::TcpConnect => Self::TcpConnect,
            ProbeKind::TlsHello => Self::TlsHello,
            // `ProbeKind` is `#[non_exhaustive]`; ICMP is both the default and the
            // cheapest, so an unknown future kind falling here is harmless to display.
            _ => Self::IcmpEcho,
        }
    }
}

/// How many members of a group are in each state.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct HealthCountsView {
    /// Members answering within every threshold.
    pub ok: u32,
    /// Members answering but degraded.
    pub degraded: u32,
    /// Members nothing gets through to.
    pub unreachable: u32,
    /// Members whose probes are all filtered.
    pub blocked: u32,
    /// Members proven alive by their traffic, with no probe answering.
    pub carrying_traffic: u32,
    /// Members not measured enough to judge.
    pub unknown: u32,
}

impl From<HealthCounts> for HealthCountsView {
    fn from(counts: HealthCounts) -> Self {
        // Counts are bounded by the size of a baseline list; the saturation is a formality
        // that keeps the conversion total.
        let narrow = |value: usize| u32::try_from(value).unwrap_or(u32::MAX);
        Self {
            ok: narrow(counts.ok),
            degraded: narrow(counts.degraded),
            unreachable: narrow(counts.unreachable),
            blocked: narrow(counts.blocked),
            carrying_traffic: narrow(counts.carrying_traffic),
            unknown: narrow(counts.unknown),
        }
    }
}

/// One baseline target as the dashboard shows it.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct TargetView {
    /// Identifier unique across both baselines.
    pub key: String,
    /// The operator's name for the service, shown as written.
    pub label: String,
    /// The address the list file named — a literal or a host name.
    pub written_address: String,
    /// The address actually being probed, once resolved.
    pub resolved_address: Option<String>,
    /// Whether a local tunnel remaps this endpoint, so its figure is end-to-end through
    /// the tunnel rather than a round trip to the server.
    pub tunnelled: bool,
    /// Whether any probe kind can still measure it honestly.
    pub measurable: bool,
    /// Which kind is measuring it now.
    pub probe_kind: Option<ProbeKindView>,
    /// Whether a probe kind has been *proven* filtered — a later kind succeeded after an
    /// earlier one was set aside. Never claimed on silence alone.
    pub filtering_confirmed: bool,
    /// The verdict.
    pub health: HealthView,
    /// Mean round-trip time over the window, in milliseconds.
    pub rtt_ms: Option<f64>,
    /// Jitter over the window, in milliseconds.
    pub jitter_ms: Option<f64>,
    /// Packet loss over the window, as a percentage.
    pub loss_pct: Option<f64>,
    /// Seconds before now for each point of the series — negative, ascending.
    ///
    /// A real time axis rather than sample indices: probe intervals stretch under backoff,
    /// so evenly spaced points would draw a chart that lies about when things happened.
    pub series_age_secs: Vec<f64>,
    /// Round-trip time at each point, or `null` where the probe did not come back.
    pub series_rtt_ms: Vec<Option<f64>>,
}

/// One baseline, taken together.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct GroupView {
    /// Which baseline this is.
    pub group: BaselineGroup,
    /// The headline verdict.
    pub verdict: HealthView,
    /// The distribution behind it. Shown, never collapsed into the verdict.
    pub counts: HealthCountsView,
    /// Median round-trip time across the answering members, in milliseconds.
    pub rtt_ms: Option<f64>,
    /// Median jitter across the answering members, in milliseconds.
    pub jitter_ms: Option<f64>,
    /// Loss across the group, weighted by probes.
    pub loss_pct: Option<f64>,
    /// The members, in list order.
    pub targets: Vec<TargetView>,
}

impl GroupView {
    /// Builds a group view from its computed health and its members.
    #[must_use]
    pub fn new(group: BaselineGroup, health: GroupHealth, targets: Vec<TargetView>) -> Self {
        Self {
            group,
            verdict: health.verdict.into(),
            counts: health.counts.into(),
            rtt_ms: health.rtt_ms,
            jitter_ms: health.jitter_ms,
            loss_pct: health.loss_pct,
            targets,
        }
    }
}

/// What the evidence adds up to, as a network-level statement.
///
/// Every variant is a fact about a *network path*. None of them says a game is broken or a
/// company's service is down — the app cannot observe either, and claiming one would be
/// exactly the failure this product exists to avoid.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub enum VerdictView {
    /// Too little has been measured to say anything at all.
    NotEnoughEvidence,
    /// Probes are being filtered wherever they were sent, so nothing was measured.
    NothingMeasurable,
    /// Everything measured is within its thresholds.
    Clear,
    /// Services inside the user's own country are degraded or unreachable.
    LocalNetworkOrProvider,
    /// Domestic services answer normally and foreign ones do not.
    CrossBorderPath,
    /// The general network is fine and this application's own endpoints are not.
    RouteToThisApplication,
    /// The game's own reference targets have all gone silent while the network is fine.
    GameServersUnreachable,
    /// Part of the game's reference pool is silent while the rest answers.
    GameServersPartlyUnreachable,
}

impl From<Verdict> for VerdictView {
    fn from(verdict: Verdict) -> Self {
        match verdict {
            Verdict::NothingMeasurable => Self::NothingMeasurable,
            Verdict::Clear => Self::Clear,
            Verdict::LocalNetworkOrProvider => Self::LocalNetworkOrProvider,
            Verdict::CrossBorderPath => Self::CrossBorderPath,
            Verdict::RouteToThisApplication => Self::RouteToThisApplication,
            Verdict::GameServersUnreachable => Self::GameServersUnreachable,
            Verdict::GameServersPartlyUnreachable => Self::GameServersPartlyUnreachable,
            // A verdict this build has no word for must read as "we cannot say", never as
            // anything the user might act on.
            _ => Self::NotEnoughEvidence,
        }
    }
}

/// A verdict and the endpoints it actually covers.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct DiagnosisView {
    /// What the evidence says.
    pub verdict: VerdictView,
    /// Whether it is something the user can act on, as against a state of not knowing.
    ///
    /// Sent rather than derived in TypeScript, because which verdicts are actionable is a
    /// judgement and every judgement in this product lives in Rust where it is tested.
    pub actionable: bool,
    /// How many of the application's endpoints the verdict is about.
    ///
    /// Zero for a verdict about the general network. "Two of seven endpoints" is a
    /// different message from "your game is unreachable", and only one of them is true.
    pub endpoints_affected: u32,
    /// How many endpoints the application has in total.
    pub endpoints_total: u32,
}

impl From<Diagnosis> for DiagnosisView {
    fn from(diagnosis: Diagnosis) -> Self {
        let narrow = |value: usize| u32::try_from(value).unwrap_or(u32::MAX);
        Self {
            verdict: diagnosis.verdict.into(),
            actionable: diagnosis.verdict.is_actionable(),
            endpoints_affected: narrow(diagnosis.endpoints_affected),
            endpoints_total: narrow(diagnosis.endpoints_total),
        }
    }
}

/// What a monitored game's reference pool says about its own infrastructure.
///
/// The one signal that can separate "the game's servers are not answering" from "you cannot
/// reach them" — several addresses belonging to the same game, in different places, probed
/// at a trickle. Shown beside the verdict rather than instead of it: the numbers are what
/// let a user check the conclusion.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct PoolView {
    /// How many members came from the bundled seeds the operator published.
    pub seeded: u32,
    /// How many this machine learned from the game's own traffic.
    ///
    /// Distinguished from the seeds because they are different evidence: a learned member is
    /// a server this user was actually placed on, which is stronger, and it exists only
    /// because the user allowed it to be remembered.
    pub learned: u32,
    /// How many members have never answered a probe, and so speak for nothing.
    ///
    /// The normal state of a pool built from a UDP title's own match servers, which answer
    /// nothing anyone can send. They are held out of every figure below rather than counted
    /// as failures: an address with no baseline cannot tell us that something changed, and
    /// counting one would report a working game as down.
    pub unproven: u32,
    /// What the members say together.
    pub health: HealthView,
    /// The distribution behind it.
    pub counts: HealthCountsView,
    /// How many of the judged members answer, as a percentage.
    ///
    /// `null` where nothing could be judged — every probe filtered, or nothing probed yet.
    /// That must stay distinct from zero: one is an absence of knowledge and the other is a
    /// finding.
    pub answering_pct: Option<f64>,
    /// Median round-trip time across the answering members, in milliseconds.
    pub rtt_ms: Option<f64>,
}

impl PoolView {
    /// Renders one application's pool report.
    #[must_use]
    pub fn of(seeded: usize, learned: usize, reading: &PoolReading) -> Self {
        let narrow = |value: usize| u32::try_from(value).unwrap_or(u32::MAX);
        Self {
            seeded: narrow(seeded),
            learned: narrow(learned),
            unproven: narrow(reading.unproven),
            health: reading.health().into(),
            counts: reading.counts.into(),
            answering_pct: reading.answering_ratio().map(|ratio| ratio * 100.0),
            rtt_ms: reading.rtt_ms,
        }
    }
}

/// How one status check read.
///
/// A fact about a single check, never a windowed verdict — which is exactly what makes the
/// mini-timeline worth drawing beside a card: it is the evidence the headline was reached
/// from, and it keeps the four ways a check can fail to produce a number apart.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub enum CheckMarkView {
    /// It answered within the slow line.
    Answered,
    /// It answered, but slowly.
    Slow,
    /// Nothing came back in time.
    Lost,
    /// The destination answered that it cannot be reached.
    Refused,
    /// The probe kind was filtered, so this check measured nothing at all.
    Filtered,
    /// A tunnel on this machine answered instead of the service.
    ///
    /// Its own word rather than one of the four above. Read as filtering it would send a
    /// user looking for a block that is not there; read as loss — which is what the
    /// catch-all below used to do to any mark it had no word for — it would report a
    /// dropped packet where a packet was never sent.
    AnsweredLocally,
}

impl From<CheckMark> for CheckMarkView {
    fn from(mark: CheckMark) -> Self {
        match mark {
            CheckMark::Answered => Self::Answered,
            CheckMark::Slow => Self::Slow,
            CheckMark::Refused => Self::Refused,
            CheckMark::Filtered => Self::Filtered,
            CheckMark::AnsweredLocally => Self::AnsweredLocally,
            // A mark this build has no word for must not read as an answer.
            _ => Self::Lost,
        }
    }
}

/// One check on the mini-timeline.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct CheckView {
    /// Seconds before now the check completed — negative, ascending to the right-hand edge.
    ///
    /// A real time axis rather than a cell index: checks stretch under backoff, so evenly
    /// spaced cells would draw a strip that lies about when things happened.
    pub age_secs: f64,
    /// What it produced.
    pub mark: CheckMarkView,
}

/// One endpoint of one status-page service.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct ServiceEndpointView {
    /// Identifier unique across the whole service list.
    pub key: String,
    /// The address the list file named — almost always a host name.
    ///
    /// Shown rather than the resolved address, because that is what the user recognises and
    /// because a platform's front door sits on a content network whose address changes by
    /// the hour.
    pub written_address: String,
    /// The address actually being checked, once resolved. `null` means the name did not
    /// resolve — under censorship that is itself a finding, not a reason to hide the row.
    pub resolved_address: Option<String>,
    /// Whether a local tunnel remaps it, making the figure end-to-end through that tunnel
    /// rather than a round trip to the service.
    pub tunnelled: bool,
    /// Whether any probe kind can still check it honestly.
    pub measurable: bool,
    /// Which kind is checking it now.
    pub probe_kind: Option<ProbeKindView>,
    /// Whether a probe kind has been *proven* filtered here.
    pub filtering_confirmed: bool,
    /// The verdict, from the most recent checks.
    pub health: HealthView,
    /// The most recent answer's round-trip time, in milliseconds.
    pub rtt_ms: Option<f64>,
    /// Mean round-trip time across the window, in milliseconds.
    pub mean_rtt_ms: Option<f64>,
    /// Loss across the window, as a percentage.
    pub loss_pct: Option<f64>,
    /// The recent checks, oldest first.
    pub checks: Vec<CheckView>,
}

/// One status-page service, taken together.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct ServiceView {
    /// Its identifier from the list. A React key, and the tag a verdict names.
    pub id: String,
    /// The operator's name for it, shown as written.
    pub label: String,
    /// Which shelf of the page it sits on.
    pub group: ServiceGroup,
    /// The headline verdict.
    pub verdict: HealthView,
    /// The distribution behind it. Shown whenever a service has more than one endpoint,
    /// never collapsed into the verdict — a storefront that answers while the gateway does
    /// not is the finding, and one amber dot would hide which half is broken.
    pub counts: HealthCountsView,
    /// Median round-trip time across the answering endpoints, in milliseconds.
    pub rtt_ms: Option<f64>,
    /// Loss across the service, weighted by checks.
    pub loss_pct: Option<f64>,
    /// How many seconds ago the freshest check completed.
    ///
    /// Stated because a status page whose data has quietly stopped arriving looks exactly
    /// like one reporting good news. `null` before anything has been checked at all.
    pub last_checked_secs: Option<f64>,
    /// Its endpoints, in list order.
    pub endpoints: Vec<ServiceEndpointView>,
}

impl ServiceView {
    /// Builds a service view from its computed health and its endpoints.
    #[must_use]
    pub fn new(
        id: String,
        label: String,
        group: ServiceGroup,
        health: GroupHealth,
        last_checked_secs: Option<f64>,
        endpoints: Vec<ServiceEndpointView>,
    ) -> Self {
        Self {
            id,
            label,
            group,
            verdict: health.verdict.into(),
            counts: health.counts.into(),
            rtt_ms: health.rtt_ms,
            loss_pct: health.loss_pct,
            last_checked_secs,
            endpoints,
        }
    }
}

/// Transport an application reaches an endpoint over.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub enum TransportView {
    /// TCP.
    Tcp,
    /// UDP.
    Udp,
}

impl From<Transport> for TransportView {
    fn from(transport: Transport) -> Self {
        match transport {
            Transport::Tcp => Self::Tcp,
            Transport::Udp => Self::Udp,
        }
    }
}

/// Whether the application is currently using an endpoint.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub enum LivenessView {
    /// Observed recently.
    Active,
    /// Not observed for a while, but still remembered and still measured.
    Idle,
}

impl From<Liveness> for LivenessView {
    fn from(liveness: Liveness) -> Self {
        match liveness {
            Liveness::Active => Self::Active,
            Liveness::Idle => Self::Idle,
        }
    }
}

/// How often an endpoint is being probed.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub enum ProbingView {
    /// At the normal interval.
    Active,
    /// At the long interval — idle, or ranked past the per-application cap. Still measured,
    /// never dropped.
    Demoted,
}

impl From<Probing> for ProbingView {
    fn from(probing: Probing) -> Self {
        match probing {
            Probing::Active => Self::Active,
            Probing::Demoted => Self::Demoted,
        }
    }
}

/// Whether per-process flow events are available, as the UI must explain it.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub enum FlowStatusView {
    /// A tracing session is open: UDP endpoints and byte counters are being discovered.
    Active,
    /// This account may not open a tracing session.
    ///
    /// The ordinary state on Windows until the user performs the one-time setup, and the
    /// one the UI has to explain: TCP endpoints are still found, UDP ones are not, and no
    /// throughput is counted anywhere. An absent endpoint is not an absent flow.
    NotPermitted,
    /// A session was open and has stopped; the app is trying to bring it back.
    ///
    /// A tracing session is a named system object, not a possession — anything that knows
    /// the name can stop it. Until it is back, UDP endpoints and byte counters are missing
    /// exactly as though there had never been a session, and saying so is the only way the
    /// user can tell that from a game with nothing to show.
    Stopped,
    /// No flow source exists on this platform, or it failed for another reason.
    Unavailable,
}

impl From<FlowStatus> for FlowStatusView {
    fn from(status: FlowStatus) -> Self {
        match status {
            FlowStatus::Active => Self::Active,
            FlowStatus::NotPermitted => Self::NotPermitted,
            FlowStatus::Stopped => Self::Stopped,
            // A state this build has no word for must not read as "everything is fine".
            _ => Self::Unavailable,
        }
    }
}

/// What the hops of a path say together.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub enum PathQualityView {
    /// Nothing measured yet.
    NotMeasuredYet,
    /// The deepest hop that answers is within every threshold.
    Ok,
    /// Degradation shows at every answering hop, so it belongs to the path.
    Degraded,
    /// Only the deepest hop's own figure moved, and the hops before it are clean.
    ///
    /// Reported as its own state rather than as a fault: routers rate-limit echoes addressed
    /// to themselves while forwarding everything else perfectly, so this observation is real
    /// and its cause is genuinely ambiguous.
    Uncorroborated,
    /// Nothing on the path's edge answers any more — a route change, or a break short of it.
    Lost,
}

impl From<PathQuality> for PathQualityView {
    fn from(quality: PathQuality) -> Self {
        match quality {
            PathQuality::Ok => Self::Ok,
            PathQuality::Degraded => Self::Degraded,
            PathQuality::Uncorroborated => Self::Uncorroborated,
            PathQuality::Lost => Self::Lost,
            // A state this build has no word for must read as "nothing measured", never as
            // anything reassuring.
            _ => Self::NotMeasuredYet,
        }
    }
}

/// Where the route to an endpoint stops.
///
/// Position, not blame, and deliberately not a claim about a national border: naming one
/// needs the baselines to corroborate, which is the verdict engine's job.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub enum PathPositionView {
    /// The endpoint itself answered the walk; nothing stands in for it.
    Reached,
    /// Not one router answered, which usually means expiry messages are filtered locally.
    NothingAnswered,
    /// The furthest answering hop was inside the user's own network.
    InsideThisNetwork,
    /// The furthest answering hop was the provider's carrier-NAT equipment.
    InsideTheAccessNetwork,
    /// Public infrastructure, with no long-haul link crossed first.
    BeforeAnyLongHaulLink,
    /// Past a link long enough to be intercontinental.
    BeyondALongHaulLink,
}

impl From<PathEnd> for PathPositionView {
    fn from(end: PathEnd) -> Self {
        match end {
            PathEnd::Reached => Self::Reached,
            PathEnd::InsideThisNetwork { .. } => Self::InsideThisNetwork,
            PathEnd::InsideTheAccessNetwork { .. } => Self::InsideTheAccessNetwork,
            PathEnd::BeforeAnyLongHaulLink { .. } => Self::BeforeAnyLongHaulLink,
            PathEnd::BeyondALongHaulLink { .. } => Self::BeyondALongHaulLink,
            _ => Self::NothingAnswered,
        }
    }
}

/// The route to an endpoint that answers nothing, measured continuously.
///
/// **Never a round trip to the endpoint**, and the UI must never present it as one. It is the
/// round trip to the deepest router that answers on the way there, and the endpoint's own
/// distance beyond that router is unknown — it replied at no time-to-live at all. What can be
/// said is which hop this is ([`PathView::hop_ttl`]) and where it sits
/// ([`PathView::position`]), and that is what the page says.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct PathView {
    /// Distance in routers of the hop these figures belong to, or `null` when none answers.
    pub hop_ttl: Option<u32>,
    /// How many hops of the route are being probed. More than one is what makes the verdict
    /// worth anything: a single router's figure cannot corroborate itself.
    pub hops_probed: u32,
    /// Where the route stops.
    pub position: PathPositionView,
    /// What the hops say together.
    pub quality: PathQualityView,
    /// Mean round-trip time to that hop, in milliseconds.
    pub rtt_ms: Option<f64>,
    /// Jitter at that hop, in milliseconds.
    pub jitter_ms: Option<f64>,
    /// Packet loss to that hop, as a percentage.
    pub loss_pct: Option<f64>,
    /// Whose network the reported hop belongs to.
    ///
    /// The figures above say *how far* the route gets and how well; this says *whose
    /// equipment it got that far on*, which is the half that turns them into a diagnosis. A
    /// route that ends inside the user's own provider and one that ends at a border transit
    /// network produce identical numbers and mean opposite things, and until now the page
    /// could only distinguish them by position.
    ///
    /// `null` under the same conditions as an endpoint's own name, and additionally
    /// whenever no hop answered — there is then no address to look up.
    pub hop_network: Option<NetworkView>,
}

impl PathView {
    /// Renders a route reading, naming the hop it reports on.
    ///
    /// A named constructor rather than [`From`] because the directory has to be passed in:
    /// a conversion that reached for a global would put a lookup table inside a rendering
    /// function, which is the thing this layer is organised to avoid.
    #[must_use]
    pub fn of(reading: &EdgeReading, names: &NetworkNames) -> Self {
        let reported = reading.reported_hop();
        Self {
            hop_ttl: reported.map(|hop| u32::from(hop.ttl)),
            hops_probed: u32::try_from(reading.hops.len()).unwrap_or(u32::MAX),
            position: reading.end.into(),
            quality: reading.quality.into(),
            rtt_ms: reading.rtt_ms(),
            jitter_ms: reading.jitter_ms(),
            loss_pct: reading.loss_pct(),
            hop_network: reported.and_then(|hop| names.name_of(hop.address)),
        }
    }
}

/// What an endpoint's own traffic says, measured passively.
///
/// The second of the two columns an endpoint that answers nothing gets, and a different
/// quantity from the first: [`PathView`] is a round trip to a router short of the endpoint,
/// this is the arrival pattern of the data the application is actually exchanging. **Never
/// merged with it, and never called a ping.** Nothing here times a request against its
/// answer — the operating system reports that datagrams arrived, not what they replied to.
///
/// Its value is precisely that it disagrees: a clean route beside ragged arrivals is the
/// server's problem, a ragged route beside clean arrivals is a router rate-limiting the
/// probes we send it. One merged figure would destroy the only diagnosis available for an
/// endpoint nothing can be sent to.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct FlowView {
    /// How many seconds of traffic the figures cover.
    ///
    /// Stated rather than assumed: the history reaches back as far as it reaches, and a
    /// rate quoted over a period it does not cover would be an invention.
    pub span_secs: f64,
    /// Bytes per second the application sent.
    pub sent_bytes_per_sec: f64,
    /// Bytes per second that came back.
    pub received_bytes_per_sec: f64,
    /// Arrivals per second from the far end, once there are enough to say.
    ///
    /// Datagrams of one update are counted once: a server that answers a tick with two
    /// packets is sending twenty updates a second, not forty.
    pub updates_per_sec: Option<f64>,
    /// Mean interval between arrivals, in milliseconds.
    pub arrival_mean_ms: Option<f64>,
    /// How much those intervals vary, in milliseconds.
    ///
    /// **What a player feels as stutter, and not a round-trip jitter.** It folds in the
    /// far end's own send cadence: a server that skips a tick and a network that delays one
    /// are indistinguishable here, which is exactly why it is shown beside the route rather
    /// than instead of it.
    pub arrival_jitter_ms: Option<f64>,
    /// 95th-percentile interval, in milliseconds.
    pub arrival_p95_ms: Option<f64>,
    /// Longest interval in the window, in milliseconds — the worst hitch.
    pub arrival_max_ms: Option<f64>,
    /// How long nothing has come back while the application kept sending, in milliseconds.
    ///
    /// A one-way outage, seen without sending a probe. `null` while traffic flows both
    /// ways, and also whenever the application's own sending stopped — a silence of ours
    /// says nothing about theirs.
    pub stall_ms: Option<f64>,
    /// How far the return traffic has fallen behind what this endpoint itself established,
    /// as a percentage.
    ///
    /// Deliberately not called loss: only the far end knows what it sent, so a datagram
    /// that never arrived is invisible here. `null` whenever it could not be said honestly.
    pub receive_shortfall_pct: Option<f64>,
}

impl From<&nm_core::flow::FlowReading> for FlowView {
    fn from(reading: &nm_core::flow::FlowReading) -> Self {
        let arrival = reading.arrival;
        Self {
            span_secs: reading.span.as_secs_f64(),
            sent_bytes_per_sec: reading.sent.bytes_per_sec,
            received_bytes_per_sec: reading.received.bytes_per_sec,
            updates_per_sec: arrival.map(|arrival| {
                // Bounded by the ring's capacity, so the count converts exactly.
                #[allow(clippy::cast_precision_loss)]
                let bursts = arrival.bursts as f64;
                let secs = reading.span.as_secs_f64();
                if secs > 0.0 {
                    bursts / secs
                } else {
                    0.0
                }
            }),
            arrival_mean_ms: arrival.map(|arrival| arrival.mean_ms),
            arrival_jitter_ms: arrival.map(|arrival| arrival.jitter_ms),
            arrival_p95_ms: arrival.map(|arrival| arrival.p95_ms),
            arrival_max_ms: arrival.map(|arrival| arrival.max_ms),
            stall_ms: reading.stall.map(|stall| stall.as_secs_f64() * 1_000.0),
            receive_shortfall_pct: reading.receive_shortfall_pct,
        }
    }
}

/// A round trip the operating system measured on the application's own connection.
///
/// The one figure on this page that is a genuine round trip to the endpoint without a probe
/// having been sent: the transport stack times its own segments against their
/// acknowledgements and publishes the estimate. Where it exists it is better evidence than
/// anything we could send, because it is the traffic the user is actually sending, over the
/// path it is actually taking.
///
/// It is also rare and slow. It exists for TCP only — a game's UDP match server has none —
/// and arrives every few tens of seconds at best, which is why [`PassiveRttView::age_secs`]
/// travels with it. A figure that may be a minute old must not be shown as though it were
/// current.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct PassiveRttView {
    /// The stack's current smoothed estimate, in milliseconds.
    pub rtt_ms: f64,
    /// The fastest it has seen on this connection, in milliseconds.
    pub min_rtt_ms: f64,
    /// The slowest it has seen on this connection, in milliseconds.
    pub max_rtt_ms: f64,
    /// How many seconds ago it was published.
    pub age_secs: f64,
}

impl From<&PassiveRttReading> for PassiveRttView {
    fn from(reading: &PassiveRttReading) -> Self {
        Self {
            rtt_ms: reading.rtt_ms,
            min_rtt_ms: reading.min_rtt_ms,
            max_rtt_ms: reading.max_rtt_ms,
            age_secs: reading.age.as_secs_f64(),
        }
    }
}

/// Which of the two ages an endpoint's figure is.
///
/// **Not interchangeable, and the page must say which.** A TCP connection has an
/// establishment and the operating system reports when it happened; a UDP endpoint has no
/// such thing, so what can honestly be said is how long this application has been watched
/// talking to it. One field meaning whichever was available would answer the user's question
/// — is this endpoint new, or has it been there all match — with a number nobody could
/// interpret.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub enum EndpointAgeKindView {
    /// How long the connection has been established, as the transport stack reports it.
    Established,
    /// How long this application has been watched talking to the endpoint.
    Watched,
}

/// How long an endpoint has been there.
///
/// One figure at level one, with which fact it is named a level down — the two are different
/// claims and a reader who wants to know which is being made can ask.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct EndpointAgeView {
    /// The duration itself, in seconds.
    pub secs: f64,
    /// Which of the two facts it is.
    pub kind: EndpointAgeKindView,
}

impl From<EndpointAge> for EndpointAgeView {
    fn from(age: EndpointAge) -> Self {
        match age {
            EndpointAge::Established(secs) => Self {
                secs: secs.as_secs_f64(),
                kind: EndpointAgeKindView::Established,
            },
            EndpointAge::Watched(secs) => Self {
                secs: secs.as_secs_f64(),
                kind: EndpointAgeKindView::Watched,
            },
        }
    }
}

/// One endpoint of one monitored application.
///
/// Per endpoint and never rolled up. Within one application some endpoints stay clean
/// while others lose packets or go unreachable, commonly at the same moment because they
/// sit in different networks — a login service on a CDN, voice on one provider, the game
/// server on another. An application collapsed to its worst endpoint reads as "the game is
/// broken" when the game is fine; collapsed to its best, it hides the failure the user came
/// to find.
// Named independent facts, not transposable arguments — the same reasoning as
// `crate::apps::EndpointReport`, which this mirrors.
#[allow(clippy::struct_excessive_bools)]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct EndpointView {
    /// Identity, unique within the application and stable for as long as it is tracked.
    pub key: String,
    /// Where it is, as `address:port`.
    pub address: String,
    /// Whose network it is, from the bundled directory.
    ///
    /// A label rather than a figure, and the only thing on the row a person can recognise
    /// without knowing what any of the numbers mean: "Amazon" or the name of their own
    /// provider says more about where the traffic went than the address ever will.
    ///
    /// `null` where the directory is switched off, has not finished loading, or simply does
    /// not know — unallocated space, or a block announced since the snapshot. The row shows
    /// nothing in its place; there is no guess to fall back to.
    pub network: Option<NetworkView>,
    /// How the application reaches it. Part of the identity: one server can be a TCP lobby
    /// and a UDP match at once, with two independent fates.
    pub transport: TransportView,
    /// The verdict.
    pub health: HealthView,
    /// Whether the application is still using it.
    pub liveness: LivenessView,
    /// Whether it is probed at the normal interval or the long one.
    pub probing: ProbingView,
    /// Bytes exchanged recently, or `null` where nothing counts them.
    ///
    /// `null` and `0` are different answers: without a flow source there are no counters at
    /// all, and showing zero throughput for a busy game would be a lie the user cannot see
    /// through. A count rather than a rate — see [`crate::apps::AppMonitor::traffic_window`].
    ///
    /// Carried as a float because a 64-bit integer cannot cross into JavaScript intact; a
    /// byte count stays exact in a float far past any figure this window can hold.
    pub recent_bytes: Option<f64>,
    /// The local address the application's own flow leaves from.
    pub egress: Option<String>,
    /// The adapter that address belongs to, as the operating system names it to its user.
    ///
    /// Wi-Fi, Ethernet, the accelerator's own adapter — the thing a user can actually check
    /// a before-and-after comparison against. `null` where no adapter claims the address,
    /// which happens
    /// when a tunnel goes down between the snapshot and the question; a guessed name would
    /// be worse than none.
    pub egress_interface: Option<String>,
    /// The local address the probe is bound to, when it is not the one above.
    ///
    /// `null` in the ordinary case, where the probe follows the application exactly. A value
    /// here means the figure describes a *different* route, and says which — the disclosure
    /// `CLAUDE.md` requires for the case a single probe cannot represent two applications, or
    /// where a baseline was already probing the address and its binding is not ours to move.
    pub probe_egress: Option<String>,
    /// The adapter the probe's own address belongs to.
    pub probe_egress_interface: Option<String>,
    /// Whether the probe cannot be promised to follow this application's route.
    ///
    /// Disclosed, never averaged away. Where it is true, `probeEgress` says what the probe
    /// is measuring instead.
    pub egress_conflict: bool,
    /// Whether a local tunnel remaps it, making the figure end-to-end through that tunnel
    /// rather than a round trip to the server.
    pub tunnelled: bool,
    /// Whether any probe kind can still measure it honestly.
    pub measurable: bool,
    /// Whether the three probe figures below apply to this endpoint at all.
    ///
    /// **The row changes shape on this, and the distinction is *not yet* against *never*.**
    /// While the fallback chain is still trying kinds this is `true` and `rttMs`, `jitterMs`
    /// and `lossPct` are merely absent — a figure is coming, and a dash is the honest way to
    /// wait for it. Once every kind aimed at the endpoint has been ruled out it is `false`,
    /// and no probe will ever fill them in: the page then renders no round trip, no jitter
    /// and no loss rather than three dashes that read as a broken tool. That is the
    /// permanent and normal state of a game's match server, and what stands in their place —
    /// the route and the traffic itself — is already on the card.
    ///
    /// **This is not a relaxation of "absent stays absent".** That rule forbids replacing a
    /// missing figure with a nearby number, and nothing is substituted here; it does not
    /// require printing a dash forever for a quantity that will never exist.
    ///
    /// A figure that *does* exist is never hidden by it. Where the window still holds a real
    /// sample from a kind since ruled out, this stays `true` until that sample ages out, so
    /// the row only changes shape once there is nothing left to show.
    pub probes_measure_it: bool,
    /// Which kind is measuring it now.
    pub probe_kind: Option<ProbeKindView>,
    /// Whether a probe kind has been *proven* filtered here.
    pub filtering_confirmed: bool,
    /// Seconds of warm-up left before the derived figures mean anything, or `null` once
    /// there are none.
    ///
    /// The first seconds after an endpoint is discovered are the least informative it will
    /// ever have: no window is full, the fallback chain is still trying probe kinds, ranking
    /// has not run, and the passive figures need several updates before they say anything.
    /// The page states that it is warming up rather than presenting all of it as
    /// measurement.
    ///
    /// **It never hides an answer.** The health state, a proven filtering, an endpoint alive
    /// by its own traffic and a stall all arrive at full speed, because arriving fast is the
    /// point of them. Only figures that are still noisy wait.
    pub warmup_secs_remaining: Option<f64>,
    /// Mean round-trip time over the window, in milliseconds.
    pub rtt_ms: Option<f64>,
    /// Jitter over the window, in milliseconds. Withheld during warm-up.
    pub jitter_ms: Option<f64>,
    /// Packet loss over the window, as a percentage. Withheld during warm-up.
    pub loss_pct: Option<f64>,
    /// The route to it, measured continuously, when nothing about the endpoint itself can be.
    ///
    /// A second column beside the figures above, never merged into them: it belongs to a
    /// router short of the endpoint, and calling it the endpoint's ping would be the one lie
    /// this product exists not to tell. `null` for an endpoint that answers for itself, which
    /// needs no stand-in.
    pub path: Option<PathView>,
    /// What the endpoint's own traffic says, measured passively.
    ///
    /// The other of the two columns. `null` where no flow source is running — the ordinary
    /// state on a Windows machine that has not had the one-time tracing setup, where this
    /// whole column is missing and the page's banner says why — and where the application
    /// has stopped using the endpoint, since these figures cannot tell how old they are.
    pub flow: Option<FlowView>,
    /// The round trip the operating system last measured on this connection.
    ///
    /// `null` for UDP, for a tunnelled endpoint — where the stack would be timing the round
    /// trip to the user's own router, a fake-*good* figure — and wherever nothing has been
    /// published yet.
    pub passive_rtt: Option<PassiveRttView>,
    /// How long the endpoint has been there, and which fact that is.
    pub age: EndpointAgeView,
    /// Round-trip time in each slot of the application's chart, or `null` for a slot with
    /// no answer in it.
    ///
    /// Aligned to [`AppView::chart_elapsed_secs`], which every endpoint of the application
    /// shares — that shared axis is what makes "which of these is the odd one out" a
    /// question the chart can answer. Gaps stay gaps: nothing is drawn across a `null`.
    pub chart_rtt_ms: Vec<Option<f64>>,
    /// Round-trip time to the *reported hop of the route to this endpoint*, in the same
    /// slots.
    ///
    /// What keeps a silent match server on the chart instead of leaving the endpoint the
    /// whole product exists to watch as a blank row. It shares the axis with the round trips
    /// and is **not** one: it belongs to a router short of the endpoint, at an unknown
    /// distance from it, so the chart draws it distinctly and names it for what it is. All
    /// `null` for an endpoint that answers for itself and needs no stand-in.
    pub chart_path_ms: Vec<Option<f64>>,
}

impl EndpointView {
    /// Renders one endpoint report for the UI.
    ///
    /// `interfaces` names the adapters the egress addresses belong to. It is passed in
    /// rather than looked up because it is one snapshot per emission shared by every
    /// endpoint of every application, and because reading it here would put an
    /// operating-system call inside a rendering function.
    #[must_use]
    pub fn of(report: &EndpointReport, interfaces: &InterfaceNames, names: &NetworkNames) -> Self {
        let transport = TransportView::from(report.key.transport);
        // Stated only when it differs: naming the same address twice on every row would
        // bury the one case the disclosure exists for.
        let probe_egress = report
            .probe_source
            .filter(|probe| Some(*probe) != report.source);
        // A round trip survives warm-up: one reply is one real measurement of the route, and
        // the mean of a few is the mean of a few. What waits is what a short window makes
        // *unrepresentative* — the variation between samples, and a percentage whose
        // denominator is still a handful.
        let rtt_ms = report.stats.rtt.map(|rtt| rtt.mean_ms);
        let jitter_ms = report
            .warmup_remaining
            .is_none()
            .then(|| report.stats.rtt.and_then(|rtt| rtt.jitter_ms))
            .flatten();
        // Withheld where the probes say nothing about the endpoint. A match server refuses
        // every probe kind, so its window is 100 % loss — of ours, at a port the game never
        // plays over. Printing that beside "carrying traffic" would report a working server
        // as dropping everything.
        let loss_pct = (report.health.probes_describe_the_endpoint()
            && report.warmup_remaining.is_none())
        .then_some(report.stats.loss_pct)
        .flatten();
        Self {
            key: format!("{}/{}", transport_slug(transport), report.key.address),
            address: report.key.address.to_string(),
            transport,
            health: report.health.into(),
            liveness: report.liveness.into(),
            probing: report.probing.into(),
            // Lossless: a byte count needs 53 bits to exceed a float's exact range, which
            // is eight petabytes in half a minute.
            #[allow(clippy::cast_precision_loss)]
            recent_bytes: report.recent_bytes.map(|bytes| bytes as f64),
            egress: report.source.map(|source| source.to_string()),
            egress_interface: report
                .source
                .and_then(|source| interfaces.name_of(source))
                .map(str::to_owned),
            probe_egress: probe_egress.map(|probe| probe.to_string()),
            probe_egress_interface: probe_egress
                .and_then(|probe| interfaces.name_of(probe))
                .map(str::to_owned),
            egress_conflict: report.egress_conflict,
            tunnelled: report.tunnelled,
            measurable: report.measurable,
            // Never against not yet. Rust holds the chain's answer; a figure that survives
            // from a kind since ruled out keeps the block on screen until it ages out, so
            // the row never hides a real measurement in order to change shape.
            probes_measure_it: report.probes_measure_it
                || rtt_ms.is_some()
                || jitter_ms.is_some()
                || loss_pct.is_some(),
            probe_kind: report.probe_kind.map(ProbeKindView::from),
            filtering_confirmed: report.filtering_confirmed,
            warmup_secs_remaining: report
                .warmup_remaining
                .map(|remaining| remaining.as_secs_f64()),
            rtt_ms,
            jitter_ms,
            loss_pct,
            network: names.name_of(report.key.address.ip()),
            path: report.path.as_ref().map(|path| PathView::of(path, names)),
            flow: report.flow.as_ref().map(FlowView::from),
            passive_rtt: report.passive_rtt.as_ref().map(PassiveRttView::from),
            age: report.age.into(),
            chart_rtt_ms: report.chart_rtt_ms.clone(),
            chart_path_ms: report.chart_path_ms.clone(),
        }
    }
}

/// The stable part of an endpoint's key, independent of any translation.
const fn transport_slug(transport: TransportView) -> &'static str {
    match transport {
        TransportView::Tcp => "tcp",
        TransportView::Udp => "udp",
    }
}

/// Where an endpoint sits in the order the page shows.
///
/// Severity first, so the broken few are visible without hunting through a long list. An
/// endpoint nothing gets through to outranks a degraded one; both outrank an endpoint whose
/// probes are merely filtered, because filtering is an absence of knowledge rather than a
/// failure, and being told "no" is knowledge.
const fn severity(health: HealthView) -> u8 {
    match health {
        HealthView::Unreachable => 0,
        HealthView::Degraded => 1,
        HealthView::Blocked => 2,
        // Below the states that describe a problem: an endpoint proven alive by its own
        // traffic is not one the user has to do anything about, however little was measured
        // of it. Above `Ok`, because something *is* unmeasured.
        HealthView::CarryingTraffic => 3,
        HealthView::Unknown => 4,
        HealthView::Ok => 5,
    }
}

/// One transport's worth of an application's endpoints.
///
/// **The match traffic first, the supporting connections below.** During a game the
/// endpoints that decide whether it plays well are the UDP flows; a launcher's connection, a
/// content network and a telemetry host are the company they keep. Ordered by severity alone
/// they interleave, and the endpoint the user came to look at sits wherever its health
/// happened to put it.
///
/// Grouping is by transport and nothing else — no endpoint is labelled by role, because
/// everything except the transport and the traffic volume would be a guess, and a wrong
/// label on the right number is worse than no label.
///
/// **TCP is demoted, never hidden.** A blocked or throttled TCP endpoint is a first-class
/// finding: a login service or a content network with a filter on it is exactly what "I
/// cannot get into the game" looks like. The group carries its own distribution so that a
/// member worse than `Ok` is visible before anything is unfolded.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct EndpointGroupView {
    /// Which transport this group holds.
    pub transport: TransportView,
    /// How many of its members are in each state.
    pub counts: HealthCountsView,
    /// Whether anything in it is worse than `Ok`.
    ///
    /// Sent rather than derived in TypeScript: whether a group may stay folded is a
    /// judgement about what the user must not miss, and every judgement in this product
    /// lives in Rust where it is tested.
    pub needs_attention: bool,
    /// Its members, worst first.
    pub endpoints: Vec<EndpointView>,
}

impl EndpointGroupView {
    /// Collects the endpoints of one transport, worst first.
    fn of(transport: TransportView, endpoints: Vec<EndpointView>) -> Self {
        let mut counts = HealthCounts::default();
        for endpoint in &endpoints {
            counts.record(health_of(endpoint.health));
        }
        let needs_attention = endpoints
            .iter()
            .any(|endpoint| endpoint.health != HealthView::Ok);
        Self {
            transport,
            counts: counts.into(),
            needs_attention,
            endpoints,
        }
    }
}

/// The core state a view state came from, so one distribution can be counted from views.
///
/// `HealthCounts` is the core's own tally and the only implementation of "how many are in
/// each state"; a second copy over `HealthView` would be the same arithmetic drifting
/// separately. [`HealthView::Unknown`] stands for anything the core grew that this build has
/// no word for, which is what the conversion above already decided.
const fn health_of(view: HealthView) -> Health {
    match view {
        HealthView::Ok => Health::Ok,
        HealthView::Degraded => Health::Degraded,
        HealthView::Unreachable => Health::Unreachable,
        HealthView::Blocked => Health::Blocked,
        HealthView::CarryingTraffic => Health::CarryingTraffic,
        HealthView::Unknown => Health::Unknown,
    }
}

/// One process an application currently consists of.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct AppProcessView {
    /// Its identifier.
    pub pid: u32,
    /// Its executable file name.
    pub name: String,
}

/// One monitored application and everything it is talking to.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct AppView {
    /// The identity to forget it by.
    ///
    /// Not a process identifier. The user chose an application, and the processes it is
    /// made of come and go under it — a launcher exits once the title is running, an
    /// anti-cheat re-launches the game — while this stays the same for as long as the
    /// choice does.
    pub id: u32,
    /// What to call it: the preset's name for it, or the chosen executable's file name.
    pub name: String,
    /// The processes it currently consists of.
    ///
    /// Shown rather than summarised: a grouping the user cannot inspect is one they cannot
    /// correct. An empty list is a real state and says so — the application was chosen and
    /// nothing is running under it yet, which is exactly what arming the monitor before a
    /// match looks like.
    pub processes: Vec<AppProcessView>,
    /// How many of its endpoints are in each state.
    ///
    /// The headline. There is deliberately no single verdict per application: a
    /// distribution is what the page shows, because partial failure inside one application
    /// is the normal case under filtering rather than an edge case.
    pub counts: HealthCountsView,
    /// What all the evidence says together, and which endpoints it covers.
    ///
    /// The one place the app draws a conclusion rather than reporting a measurement. It is
    /// still a network-level statement: it never says the game is broken, and it says how
    /// much of the application it is about, because partial failure inside one application
    /// is the normal case under filtering rather than an edge one.
    pub diagnosis: DiagnosisView,
    /// Seconds of warm-up left before anything is concluded about this application, or
    /// `null` once there are none.
    ///
    /// The same rule as an endpoint's, one level up. The general network underneath it has
    /// been measured all along and is still reported — it is the application that has
    /// nothing to say yet, not the machine.
    pub warmup_secs_remaining: Option<f64>,
    /// What the game's own reference pool says, when it has one.
    ///
    /// `null` for a title whose operator publishes no reference address and whose servers
    /// this machine has never seen — the ordinary case for most games, and one the page must
    /// state, because an absent pool can neither report an outage nor rule one out.
    pub pool: Option<PoolView>,
    /// Seconds since monitoring began for each slot of the chart, ascending.
    ///
    /// One axis for the whole application, which is the point: a list of sparklines answers
    /// "how is this endpoint" and the question the user actually has is "which of these is
    /// the odd one out". Every endpoint's `chartRttMs` and `chartPathMs` are aligned to it.
    ///
    /// Elapsed time rather than an age, and anchored where monitoring began. A fresh
    /// application therefore draws a short line at the *left* edge and grows rightwards into
    /// a fixed axis, instead of a short line pinned to the right with empty space behind it
    /// that walks the whole picture leftwards on every emission — which is what made a line
    /// something the reader had to chase with the pointer. The ladder advances a whole slot
    /// at a time, so the picture steps once every few seconds rather than drifting.
    pub chart_elapsed_secs: Vec<f64>,
    /// Its endpoints, grouped by transport — the match traffic first — and worst first
    /// within each group.
    ///
    /// Always both groups, in that order, even when one is empty. An empty match-traffic
    /// group is a state the page has to explain rather than omit: without the one-time
    /// tracing setup there are no UDP endpoints at all, and a missing group would read as a
    /// game that plays over nothing.
    pub groups: Vec<EndpointGroupView>,
}

impl AppView {
    /// Renders one application's endpoints, worst first.
    #[must_use]
    #[allow(clippy::too_many_arguments)]
    pub fn of(
        id: u32,
        name: String,
        processes: Vec<AppProcessView>,
        chart_elapsed_secs: Vec<f64>,
        warmup_remaining: Option<Duration>,
        interfaces: &InterfaceNames,
        names: &NetworkNames,
        reports: &[EndpointReport],
        pool: Option<(usize, usize, PoolReading)>,
        baselines: (BaselineEvidence, BaselineEvidence),
    ) -> Self {
        let mut counts = HealthCounts::default();
        for report in reports {
            counts.record(report.health);
        }

        let (domestic, foreign) = baselines;
        // While the application is warming up its endpoints are simply not offered as
        // evidence. That is exactly what the verdict engine's `None` already means — "there
        // is no application to speak about" — so the banner falls back to what *is* settled:
        // the general network, measured since the session began. Nothing is invented and
        // nothing certain is hidden; the application is only not blamed yet.
        let diagnosis = nm_core::diagnosis::diagnose(&Evidence {
            domestic,
            foreign,
            app: warmup_remaining.is_none().then_some(AppEvidence {
                endpoints: counts,
                pool: pool.map(|(_, _, reading)| reading),
            }),
        });

        // Ordered by the *settled* health rather than the shown one. Health near a threshold
        // flickers — one lost packet crosses a line and the next window crosses back — and
        // sorting on that swaps the row someone is reading with its neighbour every other
        // second. The badge still changes at once, so nothing on screen is ever stale; only
        // the order waits for the change to hold. See `nm_core::settle`.
        //
        // Sorted as reports rather than as views so the settled state never has to cross the
        // IPC boundary: it explains an ordering the UI does not compute.
        let mut ordered: Vec<&EndpointReport> = reports.iter().collect();
        // Address breaks ties so the list does not reshuffle under the user's cursor every
        // time two endpoints agree about their health.
        ordered.sort_by(|left, right| {
            severity(left.order_health.into())
                .cmp(&severity(right.order_health.into()))
                .then_with(|| left.key.cmp(&right.key))
        });
        let endpoints: Vec<EndpointView> = ordered
            .into_iter()
            .map(|report| EndpointView::of(report, interfaces, names))
            .collect();
        // Partitioned after sorting, so each group keeps the one severity order rather than
        // being sorted twice by two copies of the same rule.
        let (udp, tcp): (Vec<EndpointView>, Vec<EndpointView>) = endpoints
            .into_iter()
            .partition(|endpoint| endpoint.transport == TransportView::Udp);

        Self {
            id,
            name,
            processes,
            counts: counts.into(),
            diagnosis: diagnosis.into(),
            warmup_secs_remaining: warmup_remaining.map(|remaining| remaining.as_secs_f64()),
            pool: pool.map(|(seeded, learned, reading)| PoolView::of(seeded, learned, &reading)),
            chart_elapsed_secs,
            groups: vec![
                EndpointGroupView::of(TransportView::Udp, udp),
                EndpointGroupView::of(TransportView::Tcp, tcp),
            ],
        }
    }
}

/// One application the user could choose to monitor.
///
/// **An application, not a process.** Six identical `Discord.exe` rows ask the user to pick
/// one arbitrarily, and which of them opened the socket is precisely what this product
/// exists to stop them having to know.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct ApplicationChoiceView {
    /// Stable key for this offer, unique in the listing. A React key, and stable across
    /// refreshes so a list the user is clicking in does not reshuffle.
    pub key: String,
    /// What to call it: the bundled name for it, or the executable's file name.
    pub label: String,
    /// The executable the offer was formed from.
    ///
    /// Shown beside the label wherever the two differ. A name from the bundled list is a
    /// claim about which program this is, and a user who cannot see what it was matched
    /// against cannot tell a right name on the wrong program from a right one.
    pub executable: String,
    /// Whether the label came from the bundled lists rather than being the file name.
    ///
    /// The picker offers the named ones and puts the rest behind a toggle: a machine runs
    /// several hundred processes and a handful of them are things anyone would watch, so an
    /// unfiltered list reads like a task manager. It is a fact about what the app ships and
    /// never a claim about the program — a title too new for the bundled catalogue is
    /// perfectly watchable, which is why the toggle is not optional and why the page states
    /// how many rows it is hiding rather than implying it.
    pub named: bool,
    /// The process monitoring would be seeded from.
    ///
    /// Crosses the boundary because that is what `monitor_app` takes; it is never shown as
    /// the application's identity, which is assigned only once it is being monitored.
    pub seed_pid: u32,
    /// The processes currently running under it, in identifier order.
    ///
    /// Sent rather than counted so the picker can tell whether an application is already
    /// monitored — the monitored one may hold a different process of the same group than
    /// the one that seeded it.
    pub pids: Vec<u32>,
}

/// Why the applications could not be listed.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub enum ApplicationListProblem {
    /// This build has no process enumerator for the host operating system.
    UnsupportedPlatform,
    /// The operating system refused the enumeration.
    Refused,
}

/// The applications the picker may offer.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct ApplicationListView {
    /// Running applications, by name.
    ///
    /// Unfiltered by network activity on purpose. Offering only applications that already
    /// hold a socket would hide a game the user wants to start watching *before* it
    /// connects, which is precisely when the first endpoints are worth catching.
    pub applications: Vec<ApplicationChoiceView>,
    /// What went wrong, if anything. An empty list with no problem means the machine really
    /// is running nothing.
    pub problem: Option<ApplicationListProblem>,
}
