//! What the UI is told, and nothing more.
//!
//! These are the serialisable shapes that cross the IPC boundary; their TypeScript
//! definitions are generated by `tauri-specta`. They mirror the core's own enums rather
//! than re-exporting them, which keeps `nm-core` free of serialisation concerns and keeps
//! the wire format from drifting whenever an internal type gains a field.
//!
//! Two rules run through everything here:
//!
//! * **Absent knowledge stays absent.** Every measured quantity is an [`Option`], so a
//!   target with nothing to report renders as "—" and never as `0`.
//! * **Enums, not prose.** The UI maps each variant to a translation key in an exhaustive
//!   `switch`, so a new variant is a TypeScript compile error rather than a missing string
//!   at runtime.

use nm_core::health::{GroupHealth, Health, HealthCounts};
use nm_probes::probe::ProbeKind;
use serde::{Deserialize, Serialize};
use specta::Type;

use crate::baselines::BaselineGroup;

/// How many samples of a target's history the sparkline carries.
///
/// Sixty points is a legible sparkline and, at the default five-second baseline interval,
/// five minutes of history. Larger would cost IPC bandwidth every second for detail no
/// pixel could show.
pub const SERIES_POINTS: usize = 60;

/// How something is doing — one target or a whole group.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub enum HealthView {
    /// Answering, within every threshold.
    Ok,
    /// Answering, but losing packets, slow or unstable.
    Degraded,
    /// Nothing gets through, or the destination refuses.
    Unreachable,
    /// Every probe was filtered; nothing about the link was measured.
    Blocked,
    /// Not measured enough yet to say anything.
    Unknown,
}

impl From<Health> for HealthView {
    fn from(health: Health) -> Self {
        match health {
            Health::Ok => Self::Ok,
            Health::Degraded => Self::Degraded,
            Health::Unreachable => Self::Unreachable,
            Health::Blocked => Self::Blocked,
            // A core that grows a state the UI has no word for must render as "unknown"
            // rather than as anything reassuring.
            _ => Self::Unknown,
        }
    }
}

/// Which probe kind produced a target's numbers.
///
/// Shown because it changes what the number means: a TLS figure through a tunnel is not
/// the same quantity as an ICMP round trip to a server.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub enum ProbeKindView {
    /// An ICMP echo.
    IcmpEcho,
    /// A bare TCP connection attempt.
    TcpConnect,
    /// A TLS `ClientHello`, timed to the first answering byte.
    TlsHello,
}

impl From<ProbeKind> for ProbeKindView {
    fn from(kind: ProbeKind) -> Self {
        match kind {
            ProbeKind::TcpConnect => Self::TcpConnect,
            ProbeKind::TlsHello => Self::TlsHello,
            // `ProbeKind` is `#[non_exhaustive]`; ICMP is both the default and the
            // cheapest, so an unknown future kind falling here is harmless to display.
            _ => Self::IcmpEcho,
        }
    }
}

/// How many members of a group are in each state.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct HealthCountsView {
    /// Members answering within every threshold.
    pub ok: u32,
    /// Members answering but degraded.
    pub degraded: u32,
    /// Members nothing gets through to.
    pub unreachable: u32,
    /// Members whose probes are all filtered.
    pub blocked: u32,
    /// Members not measured enough to judge.
    pub unknown: u32,
}

impl From<HealthCounts> for HealthCountsView {
    fn from(counts: HealthCounts) -> Self {
        // Counts are bounded by the size of a baseline list; the saturation is a formality
        // that keeps the conversion total.
        let narrow = |value: usize| u32::try_from(value).unwrap_or(u32::MAX);
        Self {
            ok: narrow(counts.ok),
            degraded: narrow(counts.degraded),
            unreachable: narrow(counts.unreachable),
            blocked: narrow(counts.blocked),
            unknown: narrow(counts.unknown),
        }
    }
}

/// One baseline target as the dashboard shows it.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct TargetView {
    /// Identifier unique across both baselines.
    pub key: String,
    /// The operator's name for the service, shown as written.
    pub label: String,
    /// The address the list file named — a literal or a host name.
    pub written_address: String,
    /// The address actually being probed, once resolved.
    pub resolved_address: Option<String>,
    /// Whether a local tunnel remaps this endpoint, so its figure is end-to-end through
    /// the tunnel rather than a round trip to the server.
    pub tunnelled: bool,
    /// Whether any probe kind can still measure it honestly.
    pub measurable: bool,
    /// Which kind is measuring it now.
    pub probe_kind: Option<ProbeKindView>,
    /// Whether a probe kind has been *proven* filtered — a later kind succeeded after an
    /// earlier one was set aside. Never claimed on silence alone.
    pub filtering_confirmed: bool,
    /// The verdict.
    pub health: HealthView,
    /// Mean round-trip time over the window, in milliseconds.
    pub rtt_ms: Option<f64>,
    /// Jitter over the window, in milliseconds.
    pub jitter_ms: Option<f64>,
    /// Packet loss over the window, as a percentage.
    pub loss_pct: Option<f64>,
    /// Seconds before now for each point of the series — negative, ascending.
    ///
    /// A real time axis rather than sample indices: probe intervals stretch under backoff,
    /// so evenly spaced points would draw a chart that lies about when things happened.
    pub series_age_secs: Vec<f64>,
    /// Round-trip time at each point, or `null` where the probe did not come back.
    pub series_rtt_ms: Vec<Option<f64>>,
}

/// One baseline, taken together.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct GroupView {
    /// Which baseline this is.
    pub group: BaselineGroup,
    /// The headline verdict.
    pub verdict: HealthView,
    /// The distribution behind it. Shown, never collapsed into the verdict.
    pub counts: HealthCountsView,
    /// Median round-trip time across the answering members, in milliseconds.
    pub rtt_ms: Option<f64>,
    /// Median jitter across the answering members, in milliseconds.
    pub jitter_ms: Option<f64>,
    /// Loss across the group, weighted by probes.
    pub loss_pct: Option<f64>,
    /// The members, in list order.
    pub targets: Vec<TargetView>,
}

impl GroupView {
    /// Builds a group view from its computed health and its members.
    #[must_use]
    pub fn new(group: BaselineGroup, health: GroupHealth, targets: Vec<TargetView>) -> Self {
        Self {
            group,
            verdict: health.verdict.into(),
            counts: health.counts.into(),
            rtt_ms: health.rtt_ms,
            jitter_ms: health.jitter_ms,
            loss_pct: health.loss_pct,
            targets,
        }
    }
}
