// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Reports what the Rust core is and which platform backend it will use. */
	coreStatus: () => __TAURI_INVOKE<CoreStatus>("core_status"),
};

/** Events */
export const events = {
	coreHeartbeat: makeEvent<CoreHeartbeat>("core-heartbeat"),
};

/* Types */
/**
 *  Liveness signal proving the Rust core is running and the event channel is wired.
 * 
 *  Phase 0's demo event; the metric streams of later phases replace its role in the UI
 *  but follow the same shape — Rust-driven, typed, batched.
 */
export type CoreHeartbeat = {
	/**  Monotonically increasing tick counter, wrapping at [`u32::MAX`]. */
	seq: number,
	/**  Whole seconds since the core started, measured on a monotonic clock. */
	uptimeSecs: number,
};

/**  Whether the core can actually monitor on this machine. */
export type CoreReadiness = 
/**  The core started and has a platform backend. */
"ready" | 
/**  The core started but there is no backend for this operating system. */
"unsupportedPlatform";

/**  Static information about the monitoring core, requested by the UI on startup. */
export type CoreStatus = {
	/**  Semantic version reported by `nm-core`. */
	coreVersion: string,
	/**  Platform backend in use. */
	platform: PlatformKind,
	/**  Readiness of the core. */
	readiness: CoreReadiness,
};

/**
 *  Platform backend the core will use, as seen across the IPC boundary.
 * 
 *  Mirrors [`HostPlatform`] plus the honest "we have no backend here" case, keeping the
 *  OS-layer type out of the IPC contract.
 */
export type PlatformKind = 
/**  Windows. */
"windows" | 
/**  Linux. */
"linux" | 
/**  macOS. */
"macOs" | 
/**  An operating system `nm-platform` has no implementation for. */
"unsupported";

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

