// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Reports what the Rust core is and which platform backend it will use. */
	coreStatus: () => __TAURI_INVOKE<CoreStatus>("core_status"),
	/**  Reports the current settings. */
	getSettings: () => __TAURI_INVOKE<SettingsView>("get_settings"),
	/**
	 *  Applies new settings and reports what actually took effect.
	 * 
	 *  The return value is the sanitized result, not an echo of the request: an out-of-range
	 *  interval or an unknown country comes back corrected, and the autostart flag comes back
	 *  as the platform reports it. A UI that showed the request rather than the outcome would
	 *  be claiming something about the machine that may not be true.
	 */
	setSettings: (settings: Settings) => __TAURI_INVOKE<SettingsView>("set_settings", { settings }),
	/**
	 *  Lists the applications the user could choose to monitor.
	 * 
	 *  **Applications, not processes.** The raw process list of a desktop is six identical
	 *  `Discord.exe` rows and eighty `svchost.exe` ones, and picking one of them is a question
	 *  nobody wants to answer — they want to watch Discord. The same grouping the monitor uses
	 *  is applied here, minus the descendant rule, which only makes sense once a choice has
	 *  been made (see [`crate::applications::candidates`]).
	 * 
	 *  Read-only and handle-free: the sweep reports identity without opening a process, so an
	 *  anti-cheat system has nothing to see. Called when the picker opens and when the user
	 *  refreshes it — never on a timer, because a process list is a snapshot the moment it is
	 *  taken and polling one would spend budget to be no less stale.
	 */
	listApplications: () => __TAURI_INVOKE<ApplicationListView>("list_applications"),
	/**
	 *  Starts monitoring the application a running process belongs to.
	 * 
	 *  The process identifier is the **seed**, not the identity. What gets monitored is the
	 *  application formed around it — every process running the same executable, every
	 *  descendant of those, and anything a bundled preset joins to them — and that application
	 *  keeps the identity reported in [`crate::AppEndpoints`] as its processes come and go. A
	 *  process that has already exited, one already part of a monitored application, or one
	 *  chosen past the five-application cap is simply not adopted; the picker shows what is
	 *  monitored, so the outcome is visible without an error to report.
	 */
	monitorApp: (pid: number) => __TAURI_INVOKE<void>("monitor_app", { pid }),
	/**
	 *  Stops following one application, releasing the endpoints nothing else is measuring.
	 * 
	 *  Takes the application identity from [`crate::AppEndpoints`], not a process identifier:
	 *  the process the user originally picked may be long gone while the application is still
	 *  being watched through its children.
	 */
	forgetApp: (app: number) => __TAURI_INVOKE<void>("forget_app", { app }),
	/**
	 *  Gives the tray menu its labels, translated by the UI.
	 * 
	 *  Returns whether the menu is now in place. It is deliberately not an error type: a tray
	 *  menu that could not be built is visible as its own absence, and there is nothing the
	 *  user could do with a message about it — but the UI does need to know, because until it
	 *  succeeds, closing the window quits instead of minimizing.
	 */
	applyTrayLabels: (labels: TrayLabels) => __TAURI_INVOKE<boolean>("apply_tray_labels", { labels }),
	/**  Hides the window, leaving the core measuring. */
	hideToTray: () => __TAURI_INVOKE<void>("hide_to_tray"),
	/**
	 *  Ends the application.
	 * 
	 *  Exists so the UI can offer a quit that is always reachable, whatever state the tray menu
	 *  is in.
	 */
	quitApp: () => __TAURI_INVOKE<void>("quit_app"),
};

/** Events */
export const events = {
	appEndpoints: makeEvent<AppEndpoints>("app-endpoints"),
	coreHeartbeat: makeEvent<CoreHeartbeat>("core-heartbeat"),
	networkHealth: makeEvent<NetworkHealth>("network-health"),
	serviceStatus: makeEvent<ServiceStatus>("service-status"),
};

/* Types */
/**
 *  What every monitored application is talking to, and how each of those paths is doing.
 * 
 *  Emitted on the same beat as [`NetworkHealth`], and like it, not at all while the window
 *  is hidden. Sent even when nothing is monitored: the page still has to say whether flow
 *  events are available, which decides whether an empty list means "this application has no
 *  UDP endpoints" or "this machine cannot see UDP endpoints at all".
 */
export type AppEndpoints = {
	/**  Length of the window every figure is computed over, in seconds. */
	windowSecs: number,
	/**  Span the byte counts accumulate over, in seconds. */
	trafficWindowSecs: number,
	/**
	 *  How much time one slot of the per-application chart covers, in seconds.
	 * 
	 *  Stated because it changes what a point *means*: each one is the slowest round trip
	 *  inside its slot, and a break is a slot in which nothing answered. Both need the width
	 *  of a slot to be readable.
	 */
	chartStepSecs: number,
	/**  Whether per-process flow events are available, and if not, why. */
	flowStatus: FlowStatusView,
	/**  The monitored applications, in the order they were chosen. */
	apps: AppView[],
};

/**  One process an application currently consists of. */
export type AppProcessView = {
	/**  Its identifier. */
	pid: number,
	/**  Its executable file name. */
	name: string,
};

/**  One monitored application and everything it is talking to. */
export type AppView = {
	/**
	 *  The identity to forget it by.
	 * 
	 *  Not a process identifier. The user chose an application, and the processes it is
	 *  made of come and go under it — a launcher exits once the title is running, an
	 *  anti-cheat re-launches the game — while this stays the same for as long as the
	 *  choice does.
	 */
	id: number,
	/**  What to call it: the preset's name for it, or the chosen executable's file name. */
	name: string,
	/**
	 *  The processes it currently consists of.
	 * 
	 *  Shown rather than summarised: a grouping the user cannot inspect is one they cannot
	 *  correct. An empty list is a real state and says so — the application was chosen and
	 *  nothing is running under it yet, which is exactly what arming the monitor before a
	 *  match looks like.
	 */
	processes: AppProcessView[],
	/**
	 *  How many of its endpoints are in each state.
	 * 
	 *  The headline. There is deliberately no single verdict per application: a
	 *  distribution is what the page shows, because partial failure inside one application
	 *  is the normal case under filtering rather than an edge case.
	 */
	counts: HealthCountsView,
	/**
	 *  What all the evidence says together, and which endpoints it covers.
	 * 
	 *  The one place the app draws a conclusion rather than reporting a measurement. It is
	 *  still a network-level statement: it never says the game is broken, and it says how
	 *  much of the application it is about, because partial failure inside one application
	 *  is the normal case under filtering rather than an edge one.
	 */
	diagnosis: DiagnosisView,
	/**
	 *  What the game's own reference pool says, when it has one.
	 * 
	 *  `null` for a title whose operator publishes no reference address and whose servers
	 *  this machine has never seen — the ordinary case for most games, and one the page must
	 *  state, because an absent pool can neither report an outage nor rule one out.
	 */
	pool: PoolView | null,
	/**
	 *  Seconds before now for each slot of the chart, negative and ascending.
	 * 
	 *  One axis for the whole application, which is the point: a list of sparklines answers
	 *  "how is this endpoint" and the question the user actually has is "which of these is
	 *  the odd one out". Every endpoint's `chartRttMs` and `chartPathMs` are aligned to it.
	 */
	chartAgeSecs: (number | null)[],
	/**  Its endpoints, worst first. */
	endpoints: EndpointView[],
};

/**
 *  One application the user could choose to monitor.
 * 
 *  **An application, not a process.** Six identical `Discord.exe` rows ask the user to pick
 *  one arbitrarily, and which of them opened the socket is precisely what this product
 *  exists to stop them having to know.
 */
export type ApplicationChoiceView = {
	/**
	 *  Stable key for this offer, unique in the listing. A React key, and stable across
	 *  refreshes so a list the user is clicking in does not reshuffle.
	 */
	key: string,
	/**  What to call it: the preset's name, or the executable's file name. */
	label: string,
	/**
	 *  The process monitoring would be seeded from.
	 * 
	 *  Crosses the boundary because that is what `monitor_app` takes; it is never shown as
	 *  the application's identity, which is assigned only once it is being monitored.
	 */
	seedPid: number,
	/**
	 *  The processes currently running under it, in identifier order.
	 * 
	 *  Sent rather than counted so the picker can tell whether an application is already
	 *  monitored — the monitored one may hold a different process of the same group than
	 *  the one that seeded it.
	 */
	pids: number[],
};

/**  Why the applications could not be listed. */
export type ApplicationListProblem = 
/**  This build has no process enumerator for the host operating system. */
"unsupportedPlatform" | 
/**  The operating system refused the enumeration. */
"refused";

/**  The applications the picker may offer. */
export type ApplicationListView = {
	/**
	 *  Running applications, by name.
	 * 
	 *  Unfiltered by network activity on purpose. Offering only applications that already
	 *  hold a socket would hide a game the user wants to start watching *before* it
	 *  connects, which is precisely when the first endpoints are worth catching.
	 */
	applications: ApplicationChoiceView[],
	/**
	 *  What went wrong, if anything. An empty list with no problem means the machine really
	 *  is running nothing.
	 */
	problem: ApplicationListProblem | null,
};

/**  Which baseline a target belongs to. */
export type BaselineGroup = 
/**  Expected to be reachable inside the user's country. */
"domestic" | 
/**  Typically degraded or blocked at the country's border. */
"foreign";

/**
 *  How one status check read.
 * 
 *  A fact about a single check, never a windowed verdict — which is exactly what makes the
 *  mini-timeline worth drawing beside a card: it is the evidence the headline was reached
 *  from, and it keeps the four ways a check can fail to produce a number apart.
 */
export type CheckMarkView = 
/**  It answered within the slow line. */
"answered" | 
/**  It answered, but slowly. */
"slow" | 
/**  Nothing came back in time. */
"lost" | 
/**  The destination answered that it cannot be reached. */
"refused" | 
/**  The probe kind was filtered, so this check measured nothing at all. */
"filtered";

/**  One check on the mini-timeline. */
export type CheckView = {
	/**
	 *  Seconds before now the check completed — negative, ascending to the right-hand edge.
	 * 
	 *  A real time axis rather than a cell index: checks stretch under backoff, so evenly
	 *  spaced cells would draw a strip that lies about when things happened.
	 */
	ageSecs: number | null,
	/**  What it produced. */
	mark: CheckMarkView,
};

/**
 *  Liveness signal proving the Rust core is running and the event channel is wired.
 * 
 *  Phase 0's demo event, kept because it is the one thing that distinguishes "nothing has
 *  happened yet" from "the core is gone" before the first measurement lands.
 */
export type CoreHeartbeat = {
	/**  Monotonically increasing tick counter, wrapping at [`u32::MAX`]. */
	seq: number,
	/**  Whole seconds since the core started, measured on a monotonic clock. */
	uptimeSecs: number,
};

/**  Whether the core can actually monitor on this machine. */
export type CoreReadiness = 
/**  The core started and has a platform backend. */
"ready" | 
/**  The core started but there is no backend for this operating system. */
"unsupportedPlatform";

/**  Static information about the monitoring core, requested by the UI on startup. */
export type CoreStatus = {
	/**  Semantic version reported by `nm-core`. */
	coreVersion: string,
	/**  Platform backend in use. */
	platform: PlatformKind,
	/**  Readiness of the core. */
	readiness: CoreReadiness,
};

/**  A verdict and the endpoints it actually covers. */
export type DiagnosisView = {
	/**  What the evidence says. */
	verdict: VerdictView,
	/**
	 *  Whether it is something the user can act on, as against a state of not knowing.
	 * 
	 *  Sent rather than derived in TypeScript, because which verdicts are actionable is a
	 *  judgement and every judgement in this product lives in Rust where it is tested.
	 */
	actionable: boolean,
	/**
	 *  How many of the application's endpoints the verdict is about.
	 * 
	 *  Zero for a verdict about the general network. "Two of seven endpoints" is a
	 *  different message from "your game is unreachable", and only one of them is true.
	 */
	endpointsAffected: number,
	/**  How many endpoints the application has in total. */
	endpointsTotal: number,
};

/**
 *  One endpoint of one monitored application.
 * 
 *  Per endpoint and never rolled up. Within one application some endpoints stay clean
 *  while others lose packets or go unreachable, commonly at the same moment because they
 *  sit in different networks — a login service on a CDN, voice on one provider, the game
 *  server on another. An application collapsed to its worst endpoint reads as "the game is
 *  broken" when the game is fine; collapsed to its best, it hides the failure the user came
 *  to find.
 */
export type EndpointView = {
	/**  Identity, unique within the application and stable for as long as it is tracked. */
	key: string,
	/**  Where it is, as `address:port`. */
	address: string,
	/**
	 *  How the application reaches it. Part of the identity: one server can be a TCP lobby
	 *  and a UDP match at once, with two independent fates.
	 */
	transport: TransportView,
	/**  The verdict. */
	health: HealthView,
	/**  Whether the application is still using it. */
	liveness: LivenessView,
	/**  Whether it is probed at the normal interval or the long one. */
	probing: ProbingView,
	/**
	 *  Bytes exchanged recently, or `null` where nothing counts them.
	 * 
	 *  `null` and `0` are different answers: without a flow source there are no counters at
	 *  all, and showing zero throughput for a busy game would be a lie the user cannot see
	 *  through. A count rather than a rate — see [`crate::apps::AppMonitor::traffic_window`].
	 * 
	 *  Carried as a float because a 64-bit integer cannot cross into JavaScript intact; a
	 *  byte count stays exact in a float far past any figure this window can hold.
	 */
	recentBytes: number | null,
	/**  The local address the application's own flow leaves from. */
	egress: string | null,
	/**
	 *  The adapter that address belongs to, as the operating system names it to its user.
	 * 
	 *  Wi-Fi, Ethernet, the accelerator's own adapter — the thing a user can actually check
	 *  a before-and-after comparison against. `null` where no adapter claims the address,
	 *  which happens
	 *  when a tunnel goes down between the snapshot and the question; a guessed name would
	 *  be worse than none.
	 */
	egressInterface: string | null,
	/**
	 *  The local address the probe is bound to, when it is not the one above.
	 * 
	 *  `null` in the ordinary case, where the probe follows the application exactly. A value
	 *  here means the figure describes a *different* route, and says which — the disclosure
	 *  `CLAUDE.md` requires for the case a single probe cannot represent two applications, or
	 *  where a baseline was already probing the address and its binding is not ours to move.
	 */
	probeEgress: string | null,
	/**  The adapter the probe's own address belongs to. */
	probeEgressInterface: string | null,
	/**
	 *  Whether the probe cannot be promised to follow this application's route.
	 * 
	 *  Disclosed, never averaged away. Where it is true, `probeEgress` says what the probe
	 *  is measuring instead.
	 */
	egressConflict: boolean,
	/**
	 *  Whether a local tunnel remaps it, making the figure end-to-end through that tunnel
	 *  rather than a round trip to the server.
	 */
	tunnelled: boolean,
	/**  Whether any probe kind can still measure it honestly. */
	measurable: boolean,
	/**  Which kind is measuring it now. */
	probeKind: ProbeKindView | null,
	/**  Whether a probe kind has been *proven* filtered here. */
	filteringConfirmed: boolean,
	/**  Mean round-trip time over the window, in milliseconds. */
	rttMs: number | null,
	/**  Jitter over the window, in milliseconds. */
	jitterMs: number | null,
	/**  Packet loss over the window, as a percentage. */
	lossPct: number | null,
	/**
	 *  The route to it, measured continuously, when nothing about the endpoint itself can be.
	 * 
	 *  A second column beside the figures above, never merged into them: it belongs to a
	 *  router short of the endpoint, and calling it the endpoint's ping would be the one lie
	 *  this product exists not to tell. `null` for an endpoint that answers for itself, which
	 *  needs no stand-in.
	 */
	path: PathView | null,
	/**
	 *  What the endpoint's own traffic says, measured passively.
	 * 
	 *  The other of the two columns. `null` where no flow source is running — the ordinary
	 *  state on a Windows machine that has not had the one-time tracing setup, where this
	 *  whole column is missing and the page's banner says why — and where the application
	 *  has stopped using the endpoint, since these figures cannot tell how old they are.
	 */
	flow: FlowView | null,
	/**
	 *  The round trip the operating system last measured on this connection.
	 * 
	 *  `null` for UDP, for a tunnelled endpoint — where the stack would be timing the round
	 *  trip to the user's own router, a fake-*good* figure — and wherever nothing has been
	 *  published yet.
	 */
	passiveRtt: PassiveRttView | null,
	/**
	 *  Round-trip time in each slot of the application's chart, or `null` for a slot with
	 *  no answer in it.
	 * 
	 *  Aligned to [`AppView::chart_age_secs`], which every endpoint of the application
	 *  shares — that shared axis is what makes "which of these is the odd one out" a
	 *  question the chart can answer. Gaps stay gaps: nothing is drawn across a `null`.
	 */
	chartRttMs: (number | null)[],
	/**
	 *  Round-trip time to the *reported hop of the route to this endpoint*, in the same
	 *  slots.
	 * 
	 *  What keeps a silent match server on the chart instead of leaving the endpoint the
	 *  whole product exists to watch as a blank row. It shares the axis with the round trips
	 *  and is **not** one: it belongs to a router short of the endpoint, at an unknown
	 *  distance from it, so the chart draws it distinctly and names it for what it is. All
	 *  `null` for an endpoint that answers for itself and needs no stand-in.
	 */
	chartPathMs: (number | null)[],
};

/**  Whether per-process flow events are available, as the UI must explain it. */
export type FlowStatusView = 
/**  A tracing session is open: UDP endpoints and byte counters are being discovered. */
"active" | 
/**
 *  This account may not open a tracing session.
 * 
 *  The ordinary state on Windows until the user performs the one-time setup, and the
 *  one the UI has to explain: TCP endpoints are still found, UDP ones are not, and no
 *  throughput is counted anywhere. An absent endpoint is not an absent flow.
 */
"notPermitted" | 
/**
 *  A session was open and has stopped; the app is trying to bring it back.
 * 
 *  A tracing session is a named system object, not a possession — anything that knows
 *  the name can stop it. Until it is back, UDP endpoints and byte counters are missing
 *  exactly as though there had never been a session, and saying so is the only way the
 *  user can tell that from a game with nothing to show.
 */
"stopped" | 
/**  No flow source exists on this platform, or it failed for another reason. */
"unavailable";

/**
 *  What an endpoint's own traffic says, measured passively.
 * 
 *  The second of the two columns an endpoint that answers nothing gets, and a different
 *  quantity from the first: [`PathView`] is a round trip to a router short of the endpoint,
 *  this is the arrival pattern of the data the application is actually exchanging. **Never
 *  merged with it, and never called a ping.** Nothing here times a request against its
 *  answer — the operating system reports that datagrams arrived, not what they replied to.
 * 
 *  Its value is precisely that it disagrees: a clean route beside ragged arrivals is the
 *  server's problem, a ragged route beside clean arrivals is a router rate-limiting the
 *  probes we send it. One merged figure would destroy the only diagnosis available for an
 *  endpoint nothing can be sent to.
 */
export type FlowView = {
	/**
	 *  How many seconds of traffic the figures cover.
	 * 
	 *  Stated rather than assumed: the history reaches back as far as it reaches, and a
	 *  rate quoted over a period it does not cover would be an invention.
	 */
	spanSecs: number | null,
	/**  Bytes per second the application sent. */
	sentBytesPerSec: number | null,
	/**  Bytes per second that came back. */
	receivedBytesPerSec: number | null,
	/**
	 *  Arrivals per second from the far end, once there are enough to say.
	 * 
	 *  Datagrams of one update are counted once: a server that answers a tick with two
	 *  packets is sending twenty updates a second, not forty.
	 */
	updatesPerSec: number | null,
	/**  Mean interval between arrivals, in milliseconds. */
	arrivalMeanMs: number | null,
	/**
	 *  How much those intervals vary, in milliseconds.
	 * 
	 *  **What a player feels as stutter, and not a round-trip jitter.** It folds in the
	 *  far end's own send cadence: a server that skips a tick and a network that delays one
	 *  are indistinguishable here, which is exactly why it is shown beside the route rather
	 *  than instead of it.
	 */
	arrivalJitterMs: number | null,
	/**  95th-percentile interval, in milliseconds. */
	arrivalP95Ms: number | null,
	/**  Longest interval in the window, in milliseconds — the worst hitch. */
	arrivalMaxMs: number | null,
	/**
	 *  How long nothing has come back while the application kept sending, in milliseconds.
	 * 
	 *  A one-way outage, seen without sending a probe. `null` while traffic flows both
	 *  ways, and also whenever the application's own sending stopped — a silence of ours
	 *  says nothing about theirs.
	 */
	stallMs: number | null,
	/**
	 *  How far the return traffic has fallen behind what this endpoint itself established,
	 *  as a percentage.
	 * 
	 *  Deliberately not called loss: only the far end knows what it sent, so a datagram
	 *  that never arrived is invisible here. `null` whenever it could not be said honestly.
	 */
	receiveShortfallPct: number | null,
};

/**  One baseline, taken together. */
export type GroupView = {
	/**  Which baseline this is. */
	group: BaselineGroup,
	/**  The headline verdict. */
	verdict: HealthView,
	/**  The distribution behind it. Shown, never collapsed into the verdict. */
	counts: HealthCountsView,
	/**  Median round-trip time across the answering members, in milliseconds. */
	rttMs: number | null,
	/**  Median jitter across the answering members, in milliseconds. */
	jitterMs: number | null,
	/**  Loss across the group, weighted by probes. */
	lossPct: number | null,
	/**  The members, in list order. */
	targets: TargetView[],
};

/**  How many members of a group are in each state. */
export type HealthCountsView = {
	/**  Members answering within every threshold. */
	ok: number,
	/**  Members answering but degraded. */
	degraded: number,
	/**  Members nothing gets through to. */
	unreachable: number,
	/**  Members whose probes are all filtered. */
	blocked: number,
	/**  Members proven alive by their traffic, with no probe answering. */
	carryingTraffic: number,
	/**  Members not measured enough to judge. */
	unknown: number,
};

/**  How something is doing — one target or a whole group. */
export type HealthView = 
/**  Answering, within every threshold. */
"ok" | 
/**  Answering, but losing packets, slow or unstable. */
"degraded" | 
/**  Nothing gets through, or the destination refuses. */
"unreachable" | 
/**  Every probe was filtered; nothing about the link was measured. */
"blocked" | 
/**  Data is crossing it, but no probe answers — the normal state of a game server. */
"carryingTraffic" | 
/**  Not measured enough yet to say anything. */
"unknown";

/**  Whether the application is currently using an endpoint. */
export type LivenessView = 
/**  Observed recently. */
"active" | 
/**  Not observed for a while, but still remembered and still measured. */
"idle";

/**
 *  The general-health picture: both baselines and every target in them.
 * 
 *  Emitted once a second while the window is visible, and not at all while it is hidden —
 *  see `crate::runtime`.
 */
export type NetworkHealth = {
	/**  Whole seconds the core has been running, on a monotonic clock. */
	uptimeSecs: number,
	/**  Length of the window every figure is computed over, in seconds. */
	windowSecs: number,
	/**
	 *  What the two baselines say together.
	 * 
	 *  The comparison, not either column: domestic and foreign both failing points at the
	 *  user's own line, domestic clean with foreign failing points at the path out of the
	 *  country, and neither group means much on its own. It is the only claim on this page
	 *  that is a conclusion rather than a measurement, and it stays a claim about a
	 *  *network path* — never about a policy, a country or a company.
	 */
	diagnosis: DiagnosisView,
	/**  The baselines, domestic first. */
	groups: GroupView[],
};

/**
 *  A round trip the operating system measured on the application's own connection.
 * 
 *  The one figure on this page that is a genuine round trip to the endpoint without a probe
 *  having been sent: the transport stack times its own segments against their
 *  acknowledgements and publishes the estimate. Where it exists it is better evidence than
 *  anything we could send, because it is the traffic the user is actually sending, over the
 *  path it is actually taking.
 * 
 *  It is also rare and slow. It exists for TCP only — a game's UDP match server has none —
 *  and arrives every few tens of seconds at best, which is why [`PassiveRttView::age_secs`]
 *  travels with it. A figure that may be a minute old must not be shown as though it were
 *  current.
 */
export type PassiveRttView = {
	/**  The stack's current smoothed estimate, in milliseconds. */
	rttMs: number | null,
	/**  The fastest it has seen on this connection, in milliseconds. */
	minRttMs: number | null,
	/**  The slowest it has seen on this connection, in milliseconds. */
	maxRttMs: number | null,
	/**  How many seconds ago it was published. */
	ageSecs: number | null,
};

/**
 *  Where the route to an endpoint stops.
 * 
 *  Position, not blame, and deliberately not a claim about a national border: naming one
 *  needs the baselines to corroborate, which is the verdict engine's job.
 */
export type PathPositionView = 
/**  The endpoint itself answered the walk; nothing stands in for it. */
"reached" | 
/**  Not one router answered, which usually means expiry messages are filtered locally. */
"nothingAnswered" | 
/**  The furthest answering hop was inside the user's own network. */
"insideThisNetwork" | 
/**  The furthest answering hop was the provider's carrier-NAT equipment. */
"insideTheAccessNetwork" | 
/**  Public infrastructure, with no long-haul link crossed first. */
"beforeAnyLongHaulLink" | 
/**  Past a link long enough to be intercontinental. */
"beyondALongHaulLink";

/**  What the hops of a path say together. */
export type PathQualityView = 
/**  Nothing measured yet. */
"notMeasuredYet" | 
/**  The deepest hop that answers is within every threshold. */
"ok" | 
/**  Degradation shows at every answering hop, so it belongs to the path. */
"degraded" | 
/**
 *  Only the deepest hop's own figure moved, and the hops before it are clean.
 * 
 *  Reported as its own state rather than as a fault: routers rate-limit echoes addressed
 *  to themselves while forwarding everything else perfectly, so this observation is real
 *  and its cause is genuinely ambiguous.
 */
"uncorroborated" | 
/**  Nothing on the path's edge answers any more — a route change, or a break short of it. */
"lost";

/**
 *  The route to an endpoint that answers nothing, measured continuously.
 * 
 *  **Never a round trip to the endpoint**, and the UI must never present it as one. It is the
 *  round trip to the deepest router that answers on the way there, and the endpoint's own
 *  distance beyond that router is unknown — it replied at no time-to-live at all. What can be
 *  said is which hop this is ([`PathView::hop_ttl`]) and where it sits
 *  ([`PathView::position`]), and that is what the page says.
 */
export type PathView = {
	/**  Distance in routers of the hop these figures belong to, or `null` when none answers. */
	hopTtl: number | null,
	/**
	 *  How many hops of the route are being probed. More than one is what makes the verdict
	 *  worth anything: a single router's figure cannot corroborate itself.
	 */
	hopsProbed: number,
	/**  Where the route stops. */
	position: PathPositionView,
	/**  What the hops say together. */
	quality: PathQualityView,
	/**  Mean round-trip time to that hop, in milliseconds. */
	rttMs: number | null,
	/**  Jitter at that hop, in milliseconds. */
	jitterMs: number | null,
	/**  Packet loss to that hop, as a percentage. */
	lossPct: number | null,
};

/**
 *  Platform backend the core will use, as seen across the IPC boundary.
 * 
 *  Mirrors [`HostPlatform`] plus the honest "we have no backend here" case, keeping the
 *  OS-layer type out of the IPC contract.
 */
export type PlatformKind = 
/**  Windows. */
"windows" | 
/**  Linux. */
"linux" | 
/**  macOS. */
"macOs" | 
/**  An operating system `nm-platform` has no implementation for. */
"unsupported";

/**
 *  What a monitored game's reference pool says about its own infrastructure.
 * 
 *  The one signal that can separate "the game's servers are not answering" from "you cannot
 *  reach them" — several addresses belonging to the same game, in different places, probed
 *  at a trickle. Shown beside the verdict rather than instead of it: the numbers are what
 *  let a user check the conclusion.
 */
export type PoolView = {
	/**  How many members came from the bundled seeds the operator published. */
	seeded: number,
	/**
	 *  How many this machine learned from the game's own traffic.
	 * 
	 *  Distinguished from the seeds because they are different evidence: a learned member is
	 *  a server this user was actually placed on, which is stronger, and it exists only
	 *  because the user allowed it to be remembered.
	 */
	learned: number,
	/**  What the members say together. */
	health: HealthView,
	/**  The distribution behind it. */
	counts: HealthCountsView,
	/**
	 *  How many of the judged members answer, as a percentage.
	 * 
	 *  `null` where nothing could be judged — every probe filtered, or nothing probed yet.
	 *  That must stay distinct from zero: one is an absence of knowledge and the other is a
	 *  finding.
	 */
	answeringPct: number | null,
	/**  Median round-trip time across the answering members, in milliseconds. */
	rttMs: number | null,
};

/**
 *  Which probe kind produced a target's numbers.
 * 
 *  Shown because it changes what the number means: a TLS figure through a tunnel is not
 *  the same quantity as an ICMP round trip to a server.
 */
export type ProbeKindView = 
/**  An ICMP echo. */
"icmpEcho" | 
/**  A bare TCP connection attempt. */
"tcpConnect" | 
/**  A TLS `ClientHello`, timed to the first answering byte. */
"tlsHello";

/**  How often an endpoint is being probed. */
export type ProbingView = 
/**  At the normal interval. */
"active" | 
/**
 *  At the long interval — idle, or ranked past the per-application cap. Still measured,
 *  never dropped.
 */
"demoted";

/**  One endpoint of one status-page service. */
export type ServiceEndpointView = {
	/**  Identifier unique across the whole service list. */
	key: string,
	/**
	 *  The address the list file named — almost always a host name.
	 * 
	 *  Shown rather than the resolved address, because that is what the user recognises and
	 *  because a platform's front door sits on a content network whose address changes by
	 *  the hour.
	 */
	writtenAddress: string,
	/**
	 *  The address actually being checked, once resolved. `null` means the name did not
	 *  resolve — under censorship that is itself a finding, not a reason to hide the row.
	 */
	resolvedAddress: string | null,
	/**
	 *  Whether a local tunnel remaps it, making the figure end-to-end through that tunnel
	 *  rather than a round trip to the service.
	 */
	tunnelled: boolean,
	/**  Whether any probe kind can still check it honestly. */
	measurable: boolean,
	/**  Which kind is checking it now. */
	probeKind: ProbeKindView | null,
	/**  Whether a probe kind has been *proven* filtered here. */
	filteringConfirmed: boolean,
	/**  The verdict, from the most recent checks. */
	health: HealthView,
	/**  The most recent answer's round-trip time, in milliseconds. */
	rttMs: number | null,
	/**  Mean round-trip time across the window, in milliseconds. */
	meanRttMs: number | null,
	/**  Loss across the window, as a percentage. */
	lossPct: number | null,
	/**  The recent checks, oldest first. */
	checks: CheckView[],
};

/**  Which shelf of the status page a service sits on. */
export type ServiceGroup = 
/**  A platform a player signs in to and buys or launches games through. */
"gamingPlatform" | 
/**
 *  Infrastructure the platforms and the games themselves are hosted on.
 * 
 *  Worth separating because the two fail differently and mean different things: one
 *  storefront being unreachable is that storefront's problem, while three clouds going
 *  quiet at once is the user's route out.
 */
"infrastructure";

/**
 *  Whether each service on the status page is reachable from this machine.
 * 
 *  Emitted on the same beat as [`NetworkHealth`] and, like it, not at all while the window
 *  is hidden. The checks themselves run far slower — see
 *  [`crate::status::CHECK_INTERVAL`] — so most emissions resend the same numbers; that is
 *  the right trade against a page that would otherwise be blank for most of a minute after
 *  the user opened it.
 */
export type ServiceStatus = {
	/**
	 *  How often each endpoint is checked, in seconds.
	 * 
	 *  Stated because it is what makes "last checked" readable: a figure forty seconds old
	 *  is current at this cadence and would be stale at the dashboard's.
	 */
	checkIntervalSecs: number,
	/**  Span the latency and loss figures are computed over, in seconds. */
	windowSecs: number,
	/**  The services, in list order. */
	services: ServiceView[],
};

/**  One status-page service, taken together. */
export type ServiceView = {
	/**  Its identifier from the list. A React key, and the tag a verdict names. */
	id: string,
	/**  The operator's name for it, shown as written. */
	label: string,
	/**  Which shelf of the page it sits on. */
	group: ServiceGroup,
	/**  The headline verdict. */
	verdict: HealthView,
	/**
	 *  The distribution behind it. Shown whenever a service has more than one endpoint,
	 *  never collapsed into the verdict — a storefront that answers while the gateway does
	 *  not is the finding, and one amber dot would hide which half is broken.
	 */
	counts: HealthCountsView,
	/**  Median round-trip time across the answering endpoints, in milliseconds. */
	rttMs: number | null,
	/**  Loss across the service, weighted by checks. */
	lossPct: number | null,
	/**
	 *  How many seconds ago the freshest check completed.
	 * 
	 *  Stated because a status page whose data has quietly stopped arriving looks exactly
	 *  like one reporting good news. `null` before anything has been checked at all.
	 */
	lastCheckedSecs: number | null,
	/**  Its endpoints, in list order. */
	endpoints: ServiceEndpointView[],
};

/**
 *  Everything the user can configure.
 * 
 *  Deliberately *not* tolerant of missing fields: this type crosses the IPC boundary, and a
 *  TypeScript type whose every field is optional would let the UI send half a
 *  configuration and force every reader to guess at the rest. Tolerance for older files
 *  lives in [`Stored`] instead, where it belongs.
 */
export type Settings = {
	/**  UI language tag. */
	language: string,
	/**  Country whose domestic baseline list is monitored. */
	country: string,
	/**  Seconds between probes of one baseline target. */
	baselineIntervalSecs: number,
	/**  Whether the app starts with the user's session. Off unless asked for. */
	autostart: boolean,
	/**
	 *  Whether the addresses a monitored game connects to are remembered between sessions.
	 * 
	 *  On by default, because without it a game reference pool is only as good as what the
	 *  operator publishes — and for most titles that is nothing, leaving the app unable to
	 *  tell "the game's servers are down" from "you cannot reach them". It is a setting all
	 *  the same: it is the one thing this application writes to disk that describes what the
	 *  user plays and where, and for the people this product is for that is worth a choice
	 *  rather than an assumption. Turning it off also deletes what was already remembered.
	 */
	rememberGameServers: boolean,
};

/**
 *  What went wrong reading the settings file, if anything.
 * 
 *  Surfaced to the UI instead of being swallowed: settings silently reverting to defaults
 *  is the kind of thing a user notices a week later and never trusts again.
 */
export type SettingsProblem = 
/**  The file exists but could not be read. */
"unreadable" | 
/**  The file was read but is not valid settings; defaults are in use. */
"malformed" | 
/**  Settings could not be written back. */
"notWritable";

/**
 *  The settings in force, together with what the UI needs to offer valid choices.
 * 
 *  The bounds travel with the value rather than being duplicated in TypeScript: a slider
 *  whose limits came from a hand-written constant would drift from the ones Rust enforces.
 */
export type SettingsView = {
	/**  The settings in force. */
	settings: Settings,
	/**  What went wrong loading them, if anything. */
	problem: SettingsProblem | null,
	/**  Country codes with a bundled domestic baseline list. */
	countries: string[],
	/**  Shortest baseline interval the core accepts, in seconds. */
	minIntervalSecs: number,
	/**  Longest baseline interval the core accepts, in seconds. */
	maxIntervalSecs: number,
};

/**  One baseline target as the dashboard shows it. */
export type TargetView = {
	/**  Identifier unique across both baselines. */
	key: string,
	/**  The operator's name for the service, shown as written. */
	label: string,
	/**  The address the list file named — a literal or a host name. */
	writtenAddress: string,
	/**  The address actually being probed, once resolved. */
	resolvedAddress: string | null,
	/**
	 *  Whether a local tunnel remaps this endpoint, so its figure is end-to-end through
	 *  the tunnel rather than a round trip to the server.
	 */
	tunnelled: boolean,
	/**  Whether any probe kind can still measure it honestly. */
	measurable: boolean,
	/**  Which kind is measuring it now. */
	probeKind: ProbeKindView | null,
	/**
	 *  Whether a probe kind has been *proven* filtered — a later kind succeeded after an
	 *  earlier one was set aside. Never claimed on silence alone.
	 */
	filteringConfirmed: boolean,
	/**  The verdict. */
	health: HealthView,
	/**  Mean round-trip time over the window, in milliseconds. */
	rttMs: number | null,
	/**  Jitter over the window, in milliseconds. */
	jitterMs: number | null,
	/**  Packet loss over the window, as a percentage. */
	lossPct: number | null,
	/**
	 *  Seconds before now for each point of the series — negative, ascending.
	 * 
	 *  A real time axis rather than sample indices: probe intervals stretch under backoff,
	 *  so evenly spaced points would draw a chart that lies about when things happened.
	 */
	seriesAgeSecs: (number | null)[],
	/**  Round-trip time at each point, or `null` where the probe did not come back. */
	seriesRttMs: (number | null)[],
};

/**  Transport an application reaches an endpoint over. */
export type TransportView = 
/**  TCP. */
"tcp" | 
/**  UDP. */
"udp";

/**  Translated words for the tray menu, supplied by the UI. */
export type TrayLabels = {
	/**  "Show the window". */
	show: string,
	/**  "Quit". */
	quit: string,
};

/**
 *  What the evidence adds up to, as a network-level statement.
 * 
 *  Every variant is a fact about a *network path*. None of them says a game is broken or a
 *  company's service is down — the app cannot observe either, and claiming one would be
 *  exactly the failure this product exists to avoid.
 */
export type VerdictView = 
/**  Too little has been measured to say anything at all. */
"notEnoughEvidence" | 
/**  Probes are being filtered wherever they were sent, so nothing was measured. */
"nothingMeasurable" | 
/**  Everything measured is within its thresholds. */
"clear" | 
/**  Services inside the user's own country are degraded or unreachable. */
"localNetworkOrProvider" | 
/**  Domestic services answer normally and foreign ones do not. */
"crossBorderPath" | 
/**  The general network is fine and this application's own endpoints are not. */
"routeToThisApplication" | 
/**  The game's own reference targets have all gone silent while the network is fine. */
"gameServersUnreachable" | 
/**  Part of the game's reference pool is silent while the rest answers. */
"gameServersPartlyUnreachable";

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

